### ISSUE TITLE
Collision objects configured on tiles don't show up on map

### ISSUE THREAD

**Issue by jsprada** [bjorn/tiled#1801] opened 2017-10-26 19:34 UTC
I've configured some collisions (walls) on a tileset, but am unsure how to make them show up on the map.   I can stamp the tile images, on different layers.  I can create an object layer and manually draw my collisions on the map, but this is rather tedious.  It would be great if I can export the collisions, from the tileset, onto the map I create from it. 

Is there a way to do this?  Am I misunderstanding the feature that allows me to add collisions to a tileset?

**Comment by bjorn** [comment] 2017-10-28 21:52
They generally don't need to be visible on the map for the feature to be useful, but it would certainly be nice if there was a way to see these shapes on the map. The issue is already covered by #799, so I'll close this one.

> It would be great if I can export the collisions, from the tileset, onto the map I create from it.

The idea is that since the collision info is already stored for each tile, there would be no point in including this information repeatedly in the map file. Of course, in your game you would want to create collision shapes based on the tiles and possibly merge them together for optimization ([like Tiled2Unity does](http://www.seanba.com/megadadadventures.html)), but this is currently outside the scope of Tiled.

**Closed by bjorn** 2017-10-28 21:52 UTC

**Comment by jsprada** [comment] 2017-10-29 03:38
Thank you for the reply.  Although I do think it would be handy to see these visually on the map,  my greater concern is that the collision boundaries don't seem to show up in the .tmx file either. 

At the end of the day, I could live without the visual representation of the collision objects on the map editor, I'd really like to make use of them in my game.   If they were exported in the map file, I could do that.

**Comment by bjorn** [comment] 2017-10-29 23:01
@jsprada They aren't in the TMX file because this would be redundant. For each tile object, you have to take its collision shapes (generally from the TSX file), and rotate them by the object's rotation and offset them by the object's position (unless you're instantiating a Box2D body, in which case you'd set those properties on the body instead of changing the fixtures). And if you scale the tile objects you would take that into consideration as well. There is one tricky bit where you need to account for the origin being the bottom-left for tile objects rather than top-left.

**Comment by jsprada** [comment] 2017-10-29 23:15
@bjorn Ah, I see.  I didn't realize that the collision information was stored in the tileset, but this makes sense to me now.  Thank you!

I'm using Pygame and PyTMX to import the map files.  I'm not certain that PyTMX is doing anything with the tileset, aside from the actual image file.  Now that I know this, I will either write my own collision importer, or extend PyTMX.

Thank you for the help, and your work on building this most excellent map editor!

**Comment by bjorn** [comment] 2017-10-31 10:37
@jsprada You're welcome! I think it would be great if you could extend PyTMX to cover this.
