### ISSUE TITLE
Essential Improvements (Layer hiding, moving, hotkeys, objects,)

### ISSUE THREAD

**Issue by hepari** [bjorn/tiled#2082] opened 2019-03-07 21:11 UTC
Tiled lacks a multitude of basic but necessary features; I love the editor just for its mere existence, but please hear me out.

1. Moving multiple layers turns the order upside down. This is crazy, and makes it a useless feature.

2. I can't select a bunch of layers and simply toggle their visibility. You would think tapping H would do that, but no. The only thing I can do is toggling the visibility of all the layers. Very, very hard to live with.

3. You should be able to remap keyboard shortcuts. Everyone has their own workflow, and many shortcuts are configured in a counter-intuitive manner. It's frustrating that some functionalities have hotkeys and others have not.

4. We need a tool that selects objects by the pixel the cursor has clicked on. Maybe this isn't that simple, but this part really makes it hard working with objects.

5. We need a simple option of selecting only the objects on the selected layer. There is a reason people use layers - and it's not just to have different z-order levels. Its basic use is found in easy organization of all kinds of stuff, and that just doesn't work here.

6. We need a way to set the z-order of multiple object layers so that objects on two different layers can be displayed as if they are on the same z-order level. This would make it so much easier. (Imagine that you've got a layer for characters and a layer for furnitures. )

7. The image collection viewer. It shows five objects on a row at max. Why? The images should be automatically aligned as you move or resize the tab. (Also, we need a way to order the images by name.)

8. No one uses automapping because no one understands how it works. We need a visual editor to create and modify rules.

The editor has got many features, but only a few of them have been perfected or polished enough for public use, which is weird. I hope this list will get someone interested and urge people to have a look into it.

**Comment by bjorn** [comment] 2019-03-07 22:29
First of all thanks for the detailed feedback! As to why things are the way they are, I could explain everything. At least, you give me the impression you'd like to know. But mostly it's a result of organic growth and constant lack of time.

> 1. Moving multiple layers turns the order upside down. This is crazy, and makes it a useless feature.

I tried to reproduce this but couldn't. I used both drag-n-drop and the move Raise Layers / Lower Layers actions. Are you using the latest version?

> 2\. I can't select a bunch of layers and simply toggle their visibility. You would think tapping H would do that, but no. The only thing I can do is toggling the visibility of all the layers. Very, very hard to live with.

H toggles the highlighting and Ctrl+Shift+H toggles the non-selected layers. I guess it would make sense for Ctrl+H to toggle the visibility of the selected layers. It's not there because it didn't occur to me and nobody ever brought it up before.

> 3\. You should be able to remap keyboard shortcuts. Everyone has their own workflow, and many shortcuts are configured in a counter-intuitive manner. It's frustrating that some functionalities have hotkeys and others have not.

I did my best to set up shortcuts for those actions where it's useful and to choose intuitive ones (mostly by looking at what other applications did). Feedback is welcome, and configurable shortcuts are on the roadmap for Tiled 1.3.

> 4\. We need a tool that selects objects by the pixel the cursor has clicked on. Maybe this isn't that simple, but this part really makes it hard working with objects.

You mean clicking through transparent areas of tile objects? It's been requested before and it definitely makes sense. The main thing making it not so simple is that the selection tool can't always behave like that, though I do think it should probably behave that way by default.

> 5\. We need a simple option of selecting only the objects on the selected layer. There is a reason people use layers - and it's not just to have different z-order levels. Its basic use is found in easy organization of all kinds of stuff, and that just doesn't work here.

Yeah, currently locking all the other layers with Ctrl+Shift+L enables this behavior, but I agree there needs to be an option to do this based on what layers are currently selected.

> 6\. We need a way to set the z-order of multiple object layers so that objects on two different layers can be displayed as if they are on the same z-order level. This would make it so much easier. (Imagine that you've got a layer for characters and a layer for furnitures. )

I think that's going to be rather tricky to implement, but I agree that'd be pretty fancy.

> 7\. The image collection viewer. It shows five objects on a row at max. Why? The images should be automatically aligned as you move or resize the tab. (Also, we need a way to order the images by name.)

You can actually configure the number of columns in the tileset properties, 5 is just the default. I know it's not ideal, but the tileset view was initially written to display a tileset based on an image and keeping the positions of the tiles the same as in the image was a sensible thing to do. Indeed it makes no sense for image collection tilesets, and an alternative view that does dynamic wrapping (and sorting) is definitely in order for the image collection tilesets.

> 8\. No one uses automapping because no one understands how it works. We need a visual editor to create and modify rules.

I'm surprised by how many people actually do use automapping, but sure it is probably the most difficult feature to set up. Of course, it already features a visual editor to create and modify rules, since they're just maps. How do you imagine this could be improved?

> The editor has got many features, but only a few of them have been perfected or polished enough for public use, which is weird. I hope this list will get someone interested and urge people to have a look into it.

I think there's always room for improvement. Thanks for writing about what you care about! I will try to address a few things in the next release, but any help is appreciated!

**Comment by hepari** [comment] 2019-03-08 01:24
Oh, thank you for your quick response!

1. You are right, I'm still using our customized old version with the image collection viewer that sorts by name. :) That problem doesn't exist on the latest build!

2. Maybe people don't use the editor the way I use it...? Yes, personally I would set 'hide/show selected layer' to 'H', but Ctrl+H makes sense for the default hotkey. :)

3. The lack of hotkey customization is especially annoying to me because I like to control all hotkeys with the left hand only, which is hard if I keep switching between B, T, P and Ctrl+Shift+key. Glad to hear that it's coming up.

4. Yes, I presumed that it's more easy said than done. Still, that would be a great addition.

7. That's good to know, I'll change the number of columns right now... :) 
It would be really cool if you could prioritize that 'sorting by name' feature, as that's the only thing stopping me from upgrading. (I know, I'm being selfish!)

![capture-20190308001](https://user-images.githubusercontent.com/10383640/54000837-45bdde80-4149-11e9-82f4-67bc1c7e0def.png)

8. I've spent a lot of time staring at the samples and the guide, but I just couldn't understand it. That makes me unfit to make a suggestion for a viable automap rule editor... 

Well, thank you very much for your attention. I hope moving into your new house went smoothly!

**Comment by bjorn** [comment] 2019-05-14 09:05
> 2\. I can't select a bunch of layers and simply toggle their visibility. You would think tapping H would do that, but no. The only thing I can do is toggling the visibility of all the layers. Very, very hard to live with.

This has now been fixed by adding Ctrl+H for toggling the visibility of the selected layers (359dcb93f3a4248e0380f9965ab9dd6b44308eb9).

> 3\. You should be able to remap keyboard shortcuts. Everyone has their own workflow, and many shortcuts are configured in a counter-intuitive manner. It's frustrating that some functionalities have hotkeys and others have not.

Configurable shortcuts was implemented (#215).

> 4\. We need a tool that selects objects by the pixel the cursor has clicked on. Maybe this isn't that simple, but this part really makes it hard working with objects.

Not yet done, but covered by issue #1477.

> 5. We need a simple option of selecting only the objects on the selected layer. There is a reason people use layers - and it's not just to have different z-order levels. Its basic use is found in easy organization of all kinds of stuff, and that just doesn't work here.

Not yet done, but covered by issue #752.

> 6. We need a way to set the z-order of multiple object layers so that objects on two different layers can be displayed as if they are on the same z-order level. This would make it so much easier. (Imagine that you've got a layer for characters and a layer for furnitures. )

Opened #2126 about this.

> 7. The image collection viewer. It shows five objects on a row at max. Why? The images should be automatically aligned as you move or resize the tab. (Also, we need a way to order the images by name.)

Opened #2127 about this.

Now I'll close this feedback-list issue. Please comment/subscribe to the other issues to be notified about any progress. Thanks again for your feedback! :-)

**Closed by bjorn** 2019-05-14 09:05 UTC
