### ISSUE TITLE
Options for the grid (line thinkness, line color etc.)

### ISSUE THREAD

**Issue by Larpon** [bjorn/tiled#1471] opened 2017-03-07 10:32 UTC
I've started developing a game where scene sizes get rather big (10200x4080 pixels). I'm using these huge sizes to make sure my game will scale nicely on HiDPI devices all the way down to lower resolution devices - my engine is taking care of the actual scaling and caching of graphics.

I like having the grid visible so I can see the map/scene limits - but the large resolution make the grid a bit too dense for my taste:
![image](https://cloud.githubusercontent.com/assets/768942/23652175/2a3ad4d0-0328-11e7-935a-db75e15d2c2f.png)

It would be nice to be able give it some transparency.

The possible alternatives I've found is:
* Hiding the grid. This is a sub-optimal solution as I can't see the scene boundries.
* Use a Map width & height of 1x1 and a Tile Width/Height of 10200x4080. The limit on the Tile Width/Height are 9999px?? - so no can do
* Divide the resolution down and set the tile width/height to the divisor e.g. 2550x1020 Tile Width/Height = 4. This still gives a dense grid.

**Comment by bjorn** [comment] 2017-03-07 10:51
Your second alternative suggests that you don't really care about the tile size, so what about something in between the second and third alternative? Let's say a tile size of 40px and map size of 255x102?

I do agree grid configuration independent of the tile grid is necessary.

**Comment by bjorn** [comment] 2017-03-07 10:53
I'll close this since it's basically a duplicate of #368.

**Closed by bjorn** 2017-03-07 10:53 UTC
Labels: Feature

**Comment by Larpon** [comment] 2017-03-07 15:08
You are right - I divided it down even further - and that's better. Sorry about that :-/
