### ISSUE TITLE
Longer Object properties field

### ISSUE THREAD

**Issue by jamesrehabstudio** [bjorn/tiled#1273] opened 2016-05-09 12:54 UTC
Being able to add full multi-lined (cdata) properties would open up tiled for more complex RPG style games. At the moment, adding complicated behaviour to a specific game objects has to be done outside tiled, it would be very convenient to write scripts directly into the editor.

If I had to imagine an implementation, perhaps when you create a new custom property, where you have 'float', 'string', 'boolean', etc. there would also be 'text'. Clicking the text field would open up a popup window with a basic notepad-like interface.

Saving these properties would require property values to be placed inside the <property> element.

**Comment by bjorn** [comment] 2016-05-09 13:29
Duplicate of #205. Definitely something I'll add in the near future.

**Closed by bjorn** 2016-05-09 13:29 UTC
