### ISSUE TITLE
Trimetric maps 

### ISSUE THREAD

**Issue by ljx0517** [bjorn/tiled#1650] opened 2017-07-14 04:05 UTC
i want the editor  to support Trimetic maps .
and i copy  and modified "isometricrenderer.cpp and .h"   file.
rename it to trimetricrenderer.cpp
and seems it work 
![](https://image.ibb.co/fXYMua/1.png)
and mouse over the map.
![](https://image.ibb.co/fGM7Za/2.png)
but when i left click and want to set  image to map
![](https://image.ibb.co/iBRkLF/3.png)
i want to know ,which source file should i modify
thanks

**Comment by bjorn** [comment] 2017-07-14 08:27
Hmm, you shouldn't need to modify anything else than the renderer, so probably you still missed something. If you open a pull request with your changes I could try to help.

Btw, are the differences between `isometricrenderer.cpp` and `trimetricrenderer.cpp` big enough that it couldn't be supported by adding another parameter to the isometric renderer?

**Comment by bjorn** [comment] 2018-08-22 13:20
Closing this issue since it's a duplicate of #951.

**Closed by bjorn** 2018-08-22 13:20 UTC
Labels: feature
