### ISSUE TITLE
Bug: First custom property can't be deleted

### ISSUE THREAD

**Issue by jppresents** [bjorn/tiled#1616] opened 2017-06-17 10:10 UTC
The first custom property on objects can't be removed unless you have more than one custom property and switch between them. (This enabled the delete button for both.)
Version: Tiled 1.0.0
System: Windows 64bit

Bug demo as a gif: 
![Bug](http://i.imgur.com/qdZN1te.gif)

Behaviour: The remove button for custom properties ist not enabled when you have only one property
Expected: The button should be enabled
Workaround: Add one more property and switch between them

**Comment by bjorn** [comment] 2017-06-17 11:07
Please update, this bug was already fixed in Tiled 1.0.1.

Issue is a duplicate of #1583.

**Closed by bjorn** 2017-06-17 11:07 UTC

**Comment by jppresents** [comment] 2017-06-18 19:42
Oh sorry. 
Thank you. 👍
