### ISSUE TITLE
Tile layer compression support in JSON plugin

### ISSUE THREAD

**Issue by tcoxon** [bjorn/tiled#915] opened 2015-04-09 10:00 UTC
The map properties expose an option to compress tile layer data with gzip or zlib. The TMX output format supports these options, but the JSON plugin ignores them.

It would be useful for our project to be able to compress tile layer data in JSON files as well. In the JSON output, the "data" field in the layer object could be a Base64-encoded string, as it is in the TMX output.

**Comment by bjorn** [comment] 2015-04-09 11:11
Duplicate of #343.

**Closed by bjorn** 2015-04-09 11:11 UTC
