### ISSUE TITLE
Project specific objects configuration

### ISSUE THREAD

**Issue by dr0id** [bjorn/tiled#24] opened 2011-05-30 19:05 UTC
Hi

For level designers making it simpler to add the same object with the same properties to the map more than one time. It is a project specific description of object templates with their properties. This configuration is just an optional file referenced in the *.tmx file (multiple *.tmx files can reference the same configuration for the same project).

Full request can be found here:

https://docs.google.com/document/d/1k4KUVRZsT5klPhLGBRXSIZIhLBR-n2OxLYWnKP-tBTY/edit?hl=de&authkey=CIPK9OkO

Thanks.

**Comment by bjorn** [comment] 2017-09-06 08:20
I'm closing this issue since it's largely a duplicate of #70 and, best of all, it's mostly implemented now! The upcoming release of Tiled will support [object templates](http://doc.mapeditor.org/en/latest/manual/using-templates/), which work very much like the document linked above.

**Closed by bjorn** 2017-09-06 08:20 UTC

**Comment by bjorn** [comment] 2017-09-06 09:19
@dr0id, @AbelToy: Btw, if you are still using Tiled then any feedback on the new object templates system would be very appreciated! It was implemented by @thabetx, who took on this project as part of the Google Summer of Code.

**Comment by AbelToy** [comment] 2017-09-07 01:29
Looks great! I'm not using Tiled right now (currently not making any games requiring it), but it definitely looks wonderful from the docs, and does make me want to use Tiled for my next project!
