### ISSUE TITLE
Win 10 constant crash

### ISSUE THREAD

**Issue by Venomlemon** [bjorn/tiled#1082] opened 2015-09-14 22:21 UTC
Program worked fine with Windows 10 first, but after the first crash it stated constantly crashing every time you start it.

**Comment by bjorn** [comment] 2015-09-15 08:41
Could this be a duplicate of issue #1066? Do you remember what you did when it first crashed? Also, which version of Tiled are you using?

**Comment by Venomlemon** [comment] 2015-09-15 08:45
I was using 0.13.1 for Windows and tried to install earlier versions to fix it. I didn't try many, but now I am using daily build: tiled-2015-01-01-win32-setup.exe that doesn't have this problem.

**Comment by bjorn** [comment] 2015-09-15 08:51
So it's probably not the same issue as #1066 since that seems to be a more recent issue.

What about my second question? Without a backtrace of the crash, I don't have much hope to fix this without knowing at least how to get it to crash.

**Comment by Venomlemon** [comment] 2015-09-15 08:56
Well at first I was using Tiled quite effortlessly without crashing, I do remember having like 7-10 layers with my tileset that all were used. I first thought it might be due the map being corrupted somehow and that it kept crashing because it opens the latest project? But then I tried to open example maps, yet it did the same thing. Windows 10 just declares upon the start of the program that it had to shut the program down and it's seeking solutions for that, then shortly it just forces you to quit the program. I think I once got it to open normally by restarting computer and trying again, but while it did open up normally at first it soon started to repeat the same problem. 

This might also be some issue with Windows 10 that in itself ain't that old yet.

**Comment by obeea** [comment] 2015-09-15 12:43
I don't know if it is related but I had a similar issue recently and I resolved it by removing the registry settings, Tiled would then open again without crashing.
I figured it was just my PC but maybe there is an underlying problem somewhere using Windows 10.

**Comment by Venomlemon** [comment] 2015-09-15 12:46
I suspected that it's something to do with registery/something like that as well. Maybe worth looking in?

**Comment by bjorn** [comment] 2015-09-15 13:00
Did you enable hardware accelerated rendering by any chance? This could also cause crashes on startup, see #1085.

**Comment by Venomlemon** [comment] 2015-09-15 13:02
Ummm! Wait a minute, yeah. I think I did enable it *doh*

**Comment by bjorn** [comment] 2015-09-15 13:29
@Venomlemon Now my question is, did `tiled-2015-01-01-win32-setup.exe` not have OpenGL enabled or did it somehow not crash using that version?

**Comment by Venomlemon** [comment] 2015-09-15 13:30
That version had OpenGL on too, but somehow it doesn't crash quite as frequently. Only had like one crash with this version.

**Comment by bjorn** [comment] 2015-09-15 14:05
Hmm, alright. Well, I'll look into changing from using QGLWidget to the new QOpenGLWidget, maybe it will be better at avoiding crashes. I'm closing this issue since it's a duplicate of #525.

**Closed by bjorn** 2015-09-15 14:05 UTC
Labels: Bug
