### ISSUE TITLE
Wont stop crashing. (Locking up)

### ISSUE THREAD

**Issue by JeffFleetwood** [bjorn/tiled#1183] opened 2016-01-22 02:32 UTC
I'm running Windows 10 Home version 1511.
I've uninstalled and reinstalled a few times but it becomes unresponsive and I have to force quit.
 Any help would be great

**Comment by Ablu** [comment] 2016-01-22 09:33
Hm. This looks hard to debug with such little information...

Do you do anything specific which leads to the crash? Do you execute certain actions, open specific maps? In case you enabled OpenGl you could maybe try to run it with the `--disable-opengl` and see if that solves it.

Otherwise I fear the only solution is to compile Tiled in debug mode yourself and try to get a backtrace.

**Comment by bjorn** [comment] 2016-01-30 10:05
Can't fix this without more information, so closing the issue for now.

This may also be a duplicate of issue #1153, in which case it should help to close the 'Maps' view.

**Closed by bjorn** 2016-01-30 10:05 UTC
Labels: Bug
