### ISSUE TITLE
Please fix gms export (add isometric orientation)

### ISSUE THREAD

**Issue by all500234765** [bjorn/tiled#1795] opened 2017-10-22 06:27 UTC
Tiled supports GMS export, but only exports in Ortho orientation, but Isometric and others aren't working, cause export using ortho.
 I guess it's should be fixed...

**Comment by bjorn** [comment] 2017-10-23 07:30
Yes, this should of course be implemented. I'll close this issue since it is a duplicate of #1435.

**Closed by bjorn** 2017-10-23 07:30 UTC
