### ISSUE TITLE
Doesn't start on Mac OS 11 (Big Sur)

### ISSUE THREAD

**Issue by Astrr** [bjorn/tiled#2845] opened 2020-06-23 19:55 UTC
Everything worked fine before the update.

The icon appears in the dock and shows as "running", but no windows are ever opened. I can DM the error report to you, but can't publish it here as it contains personal information.

Tried installing both the 1.4.0 version and the snapshot, via the itch desktop client and via direct download

**Comment by bjorn** [comment] 2020-06-23 20:22
Hmm, which version were you using before? It would be interesting to know when this broke in the development snapshots. You can install old versions of those using the itch.io app (not sure how far back it goes though).

And I'm assuming that downgrading to 1.3.5 makes it work as well?

Unfortunately I can't test on macOS 11. If you think it may be helpful, you can email me the error report (email is on my profile).

**Comment by Astrr** [comment] 2020-06-25 20:14
I was using 1.4.0 on Mac OS 10.15 before, which worked OK. Looks like everything broke because of the Mac OS update, not the Tiled update.

Couldn't downgrade to 1.3.5 to test because I can only download 1.4.0 and the snapshot from itch.io
<img width="936" alt="CleanShot 2020-06-25 at 23 13 51@2x" src="https://user-images.githubusercontent.com/19356864/85790814-8b852880-b739-11ea-9581-c1391ceb4518.png">

**Comment by bjorn** [comment] 2020-06-25 20:17
@Astrr From itch.io you can only download older versions if you use the itch.io app. However, all the releases are also available at https://github.com/bjorn/tiled/releases so it's easier to download an older version from there.

Is macOS 11 already at stable release or did you install some kind of preview?

**Comment by Astrr** [comment] 2020-06-25 20:25
Oh, ok, let me check

This is a developer beta, but I don't think that it will start working again in the release version, as it seems like they intentionally changed something that the app was using

And btw, I just sent you the error report

**Comment by Astrr** [comment] 2020-06-25 20:28
Can't launch v1.3.5 at all with a macOS error "You can't open "Tiled" because it is corrupt or does not contain needed components" (translated from Russian, English error might be different)

**Comment by bjorn** [comment] 2020-06-25 20:42
> Can't launch v1.3.5 at all with a macOS error "You can't open "Tiled" because it is corrupt or does not contain needed components" (translated from Russian, English error might be different)

Hmm, I had released a broken 1.3.5 first and later updated the download. Could it be that you selected the broken 1.3.5 from the itch.io app? There should also be the fixed one, and the one on GitHub should be the fixed one.

**Comment by Astrr** [comment] 2020-06-25 21:11
Yeah, found the other 1.3.5. Same behaviour as 1.4.0. Also just in case tested 1.3.4, still nothing, just an icon in the dock.

**Comment by polycursegames** [comment] 2020-07-10 11:09
Can confirm this issue.

**Comment by bjorn** [comment] 2020-07-10 20:16
Just wondering, but does the `Tiled.app` built at https://github.com/bjorn/tiled/actions/runs/152760204 work for you? Just in case it might be a Qt issue and this is fixed in a more recent version of Qt (this Tiled.app is built against Qt 5.15 instead of Qt 5.12 like the current releases).

**Comment by polycursegames** [comment] 2020-07-10 21:06
> Just wondering, but does the `Tiled.app` built at https://github.com/bjorn/tiled/actions/runs/152760204 work for you? Just in case it might be a Qt issue and this is fixed in a more recent version of Qt (this Tiled.app is built against Qt 5.15 instead of Qt 5.12 like the current releases).

Doesn't work for me;

`dyld: Library not loaded: /usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Users/--/Downloads/Contents/MacOS/Tiled
  Reason: image not found
zsh: abort      /Users/--/Downloads/Contents/MacOS/Tiled
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

**Comment by polycursegames** [comment] 2020-07-18 13:32
https://github.com/Homebrew/homebrew-core/commit/c3f3b0182223880ed98d31a23946dbe4e2b50c83

Might shed some light on the issue?

**Comment by bjorn** [comment] 2020-07-18 19:46
@polycursegames Hmm, that patch seems to be about fixing compilation on ARM, which I don't think is related to Tiled not starting properly.

**Comment by polycursegames** [comment] 2020-07-18 20:38
> @polycursegames Hmm, that patch seems to be about fixing compilation on ARM, which I don't think is related to Tiled not starting properly.

Thats the big change on Big Sur, getting everything ready for apples chip with arm support.

**Comment by bjorn** [comment] 2020-07-19 10:18
I see they have [an open issue about Qt on Big Sur](https://bugreports.qt.io/browse/QTBUG-85546), but it doesn't list any specific issues. Most of the related issues are about Apple Silicon, either natively or through Rosetta (but you guys are just running Big Sur on amd64, right?) or universal builds (which are also only needed because of arm64).

In any case I think we should first see if we can get a build against Qt 5.15 to see if Tiled will at least run then.

**Comment by rae** [comment] 2020-07-21 03:16
If it helps, I tried downloading the Qt 5.15 version and ran it on the command line by cd'ing to `Tiled.app/Contents` and running `MacOS/Tiled`. I also tried ``MacOS/Tiled --disable-opengl`. Both times the app hung, pegging CPU usage at 100% (i.e. one core). This was on a 6-core machine.

**Comment by Astrr** [comment] 2020-07-24 02:46
>(but you guys are just running Big Sur on amd64, right?)

Yes, just a regular core i5 machine

**Comment by BastianInuk** [comment] 2020-08-18 13:25
I build v. 1.4.2 myself on Dev Beta 4, do you still experience this issue on that tiled version, works for me now.

**Comment by BastianInuk** [comment] 2020-08-18 13:30
Is this still a issue? A custom build of tiled 1.4.2 on Big Sur (beta 4) seems to be working just fine.

**Comment by bjorn** [comment] 2020-08-18 13:55
> Is this still a issue? A custom build of tiled 1.4.2 on Big Sur (beta 4) seems to be working just fine.

It may be because you probably built it against Qt 5.15. Can you try whether it also works when building against Qt 5.12, like the releases?

**Comment by FahimF** [comment] 2020-09-09 10:12
I can confirm that the release build does not work on Big Sur beta 6. The build at https://github.com/bjorn/tiled/actions/runs/152760204 is not an app - it just contains the Contents folder for the app. When I create a .app folder and put the Contents inside, it isn't recognized as a valid app. But when I go into the MacOS folder and run the _tiled_ app, I gives an error about two different versions of a framework being compiled together into the build.

When I download the source and follow the instructions to compile, the resulting app is again not recognized as an app:
![2020-09-09_06-10-49](https://user-images.githubusercontent.com/181110/92585652-ddf2d180-f2b2-11ea-945d-2335e694de23.png)

But, I can go inside the Contents/MacOS folder and launch the _tiled_ app and then it works.
![2020-09-09_06-12-05](https://user-images.githubusercontent.com/181110/92585812-11cdf700-f2b3-11ea-9b92-ef921b39c91c.png)

**Comment by FahimF** [comment] 2020-09-09 18:47
OK, I managed to figure out the the issue with the local build I made using Qt 5.15 and why the app bundle was being shown as invalid - the bundled PLIST file does not have a the executable name set. It simply says @executable@. If you change that to Tiled, then the app appears as a valid executable and runs fine.

So, as long as the app is built on Big Sur using Qt 5.15 (don't know about older versions - only tested with this), it works. Just FYI.

**Comment by bjorn** [comment] 2020-09-09 20:29
@FahimF Thank you for looking into this! So one question is, why is the replacement of these variables in the plist file not working? When I looked into it, that seemed to have something to do with using a more recent version of Qbs, and I guess the project may need to be adjusted somewhere. I'm still using an older version of Qbs for the current macOS releases to avoid this issue.

That `@executable@` problem should be independent of the problem that the current release won't run on macOS 11 though. It's good to know that that seems fixed by building against Qt 5.15, but did you try making a local build against Qt 5.12, just to make sure this is indeed what fixes it? I didn't hear back from @BastianInuk about that.

On another note, upgrading the Qt version for the releases from Qt 5.12 to Qt 5.15 will mean dropping support for macOS 10.12.

**Comment by FahimF** [comment] 2020-09-09 20:34
@bjorn Yes, I figure there's probably some setting which needs to be set (or a config file which needs updating) on Qt 5.15 to set the `@executable@` variable correctly. I haven't worked much with Qt and so don't know what it would be but if you want, will do some additional checking to figure out ...

I hadn't tried building for Qt 5.12 on Big Sur because I just had Qt 5.15 already installed via Homebrew. I guess I can try changing the Qt version and see what happens when I build. Again, would have to figure some of this out but happy to test if that would help you. Let me know.

**Comment by FahimF** [comment] 2020-09-09 22:20
@bjorn Since I was curious, I installed Qt 5.12.9 and built the source with that too. The final app again would not run immediately - the same PLIST issue:
![2020-09-09_18-04-43](https://user-images.githubusercontent.com/181110/92659942-03192b80-f317-11ea-9938-faf98fe59ed0.png)

I fixed the PLIST issue and ran the app and then it crashed. When I ran your build, there was no crash, the app would just hang. But here, I actually got a crash. Here are the details:
![2020-09-09_18-06-01](https://user-images.githubusercontent.com/181110/92659985-217f2700-f317-11ea-903c-5afde4a0fc88.png)

This issue is probably just an issue of the correct frameworks not being found since I have both Qt 5.15 and 5.12.9 on my machine. But would need to fix the issue first in order to see if any other issues manifest ....

**Comment by bjorn** [comment] 2020-09-10 07:25
@FahimF Note that the plist issue is related to the build system (Qbs), not the Qt version.

Regarding the crash, I think the interesting bits are not visible in your screenshot. Please just paste the text next time, wrapped by ` ``` ` marks.

If you think it might be related to the wrong Qt version being used or Qt not being found at all, please try running Tiled using the build system (`qbs run -p tiled`), which should run Tiled in a suitable environment.

**Comment by FahimF** [comment] 2020-09-10 10:06
@bjorn Apologies, I installed Qt Creator and qbs yesterday to compile this - hadn't worked with qbs before at all. So just reading up and figuring things as I go along. Wasn't aware that I could run Tiled using qbs. Will see if I can get that to work today if I can set up a separate environment with Qt 5.12 ...

Regarding the error, since it says at the top that it could not load the library, I figured that was clear enough 😄 I tried to get the crash to appear again just now with the same build but now it appears to just crash out with no error message. Not sure what might be causing the issue but will let you know if I can replicate things again.

**Comment by bjorn** [comment] 2020-09-10 10:10
@FahimF Ah yes, the libraries are simply missing. This is normal, if you don't run `macdeployqt` on the `Tiled.app`. But this is only needed for distribution. For running locally you should be able to either run it using Qbs or if you're using Qt Creator, just pressing the Run button there.

In Qt Creator you can configure multiple Qt versions. It should happen automatically if you install them (and Qt Creator) using the Qt Online Installer. I think Homebrew only provides the latest version.

**Comment by FahimF** [comment] 2020-09-10 10:15
@bjorn Yep 😄 That's the issue that I ran into - as in I prefer Homebrew but Homebrew only gives me Qt 5.15. If I want it to install Qt 5.12, then I have to remove the current Qt, figure out the exact commit in the Homebrew repo that had Qt 5.12 and then use that to instal Qt 5.12. I looked into it, but decided not to go that route ...

Might have to re-install Qt creator again today after all, I guess 😛 I didn't want to do it since when I added Qt 5.12 (in addition to Qt 5.15) it took ages to install and installed a lot of extra cruft. But there probably is a way to disable that. Will check today and let you know what happens when I run under Qt 5.12

**Comment by FahimF** [comment] 2020-09-10 10:34
@bjorn Just re-installed Qt Creator, compiled with Qt 5.12.9 and ran the project from within Qt Creator itself and I can confirm that it runs fine on Big Sur beta 6 😄 

So no, it doesn't look as if the Big Sur crash is due to Qt 5.12.x ... But do note that I was using Qt 5.12.9 - there was another 5.12.x version option that I didn't install or test for.

**Comment by FahimF** [comment] 2020-09-10 10:42
@bjorn Also, if it would help, I created a DMG using `macdeployqt` from the build I created. The app runs fine under Big Sur beta when I launch it from the DMG as well. So adding the link here in case you (or somebody else) can make use of it ..

https://www.transfernow.net/Svt7Gd092020

**Comment by bjorn** [comment] 2020-09-10 12:01
@FahimF I assume this build you made was using still the latest Qt Creator (and so also the latest Qbs), and you again fixed the plist manually? If so, it could be that the build will be fixed by using a newer version of Qbs - though for this we need to fix the issue with the plist file.

**Comment by FahimF** [comment] 2020-09-10 12:06
@bjorn Yes, the latest Qt Creator (and since I assume Qbs is bundled with that, the latest Qbs). And yes, I had to fix the PLIST file manually and then run `macdeployqt` to create the DMG.

Glad if this helps 😄 For the time being, I'm fine since I simply wanted to be able to use Tiled with Big Sur since I'm looking at starting a new game using Tiled ... But do ping me if you need me to test out anything further related to this - happy to help.

**Comment by bjorn** [comment] 2020-09-30 12:34
After the above two changes and 77566fc6 the artifact resulting from the macOS builds on GitHub Actions should be working just fine. Can anybody verify whether the build at https://github.com/bjorn/tiled/actions/runs/280383163 also runs on Big Sur?

**Comment by FahimF** [comment] 2020-09-30 12:38
@bjorn Can confirm that the build you linked to runs fine on Big Sur Beta 9.

**Comment by bjorn** [comment] 2020-09-30 14:04
@FahimF Alright, can we do one last test? Does the following build work on Big Sur as well, which is done against Qt 5.12.9 but with the newer version of Qbs? If it works I'll shortly release Tiled 1.4.3, which would mainly bring this fix.

[Tiled-1.4.3-macos.zip](https://github.com/bjorn/tiled/files/5306049/Tiled-1.4.3-macos.zip)

**Comment by FahimF** [comment] 2020-09-30 14:08
@bjorn Unfortunately, that one shows the original issue :( The app launches but then nothing happens and Activity Monitor shows the app as not responding. I'll leave it running for a bit to see if it eventually shows a crash report but otherwise, what I've previously had to do was force quite the app.

**Comment by bjorn** [comment] 2020-09-30 14:18
@FahimF Aw, so that probably means that upgrading to Qt 5.15 is the only readily available fix for this issue. I'll hold off on Tiled 1.4.3 for now then, people on macOS Big Sur will have to use the development snapshots (which I'll update to use Qt 5.15) and Tiled 1.5 will work on Big Sur then.

**Comment by FahimF** [comment] 2020-09-30 14:20
@bjorn Ah well. Thanks for looking into this. As long as Big Sur users have an option to keep using Tiled, I guess it shouldn't be a huge issue ...

**Comment by rae** [comment] 2020-09-30 17:49
Unlike @FahimF, the first build did not run for me on macOS Big Sur beta 9. I went into Terminal and did a `chmod +x Contents/MacOS/Tiled`, and *then* it ran ok. (Permissions had been 0664 or `rw-rw-r--`)
I had the same problems with the 1.4.3 build as described above.

**Comment by bjorn** [comment] 2020-09-30 19:32
@rae Hmm, yeah, I see this problem too, though on macOS 10.13 this did not seem to prevent the Tiled.app from running. This is a problem with the way the artifact is uploaded on GitHub Actions. I can fix it, though it will result in a double-zip.

**Comment by bjorn** [comment] 2020-10-01 13:20
@rae The executable flag issue should be fixed in [the latest artifact](https://github.com/bjorn/tiled/actions/runs/281147311), but it will now download as a zip of a zip:

![image](https://user-images.githubusercontent.com/531764/94814398-9109a300-03f9-11eb-8baf-bd75b50cedfa.png)

**Comment by bjorn** [comment] 2020-10-01 20:58
Alright, I see macOS is smart enough to extract the zip in the zip and automatically delete it as well. :-) I also noticed the download is now much smaller, since previously it was blown up due to symlinks becoming actual copies...

**Comment by bjorn** [comment] 2020-10-09 11:07
Before we finally close this issue, can somebody verify that the development snapshot I pushed to [itch.io](https://thorbjorn.itch.io/tiled) yesterday runs fine? It's the **Tiled for macOS (snapshot)**, version 2020.10.08.

Just making sure because that build is currently done on Travis CI as opposed to GitHub Actions.

**Comment by FahimF** [comment] 2020-10-09 11:12
Does not work on Big Sur beta 9 - same as before. App starts, but nothing happens and then have to force quit. But I assume you probably knew this issue would be there on Big Sur and waned this tested on Catalina?

**Comment by Astrr** [comment] 2020-10-09 11:31
> Does not work on Big Sur beta 9 - same as before. App starts, but nothing happens and then have to force quit. But I assume you probably knew this issue would be there on Big Sur and waned this tested on Catalina?

Can confirm, the snapshot uploaded 13 hours ago doesn't work on Big Sur beta 9, same behaviour.

**Comment by bjorn** [comment] 2020-10-09 13:47
Aw. So, there's probably something different in the build environment that's causing issues, rather than the Qt version. I'll need to investigate that further... Thanks for testing!

@FahimF No, the latest snapshot is built with Qbs 1.17.0 against Qt 5.15.1, same versions which are used for the build on GitHub Actions which was reported to work on Big Sur by @rae. Though, GitHub Actions pulls Qt from Homebrew whereas Travis CI uses the official Qt downloads. And there may be other differences. I think Tiled runs fine on Catalina, right?

**Comment by FahimF** [comment] 2020-10-09 13:50
@bjorn Sorry, I thought you weren't worrying about the Big Sur beta issue with this release and just wanted to test if the build worked fine on Catalina before you released - my bad for the assumption :)

Sorry about the other issues, but yes, using Qt via Homebrew on Big Sur is how I got it to compile at my end too.

**Comment by bjorn** [comment] 2020-10-29 19:23
The latest development snapshot (published yesterday) should run fine on Big Sur! I'll close this issue as soon as somebody can confirm this. :-)

**Comment by FahimF** [comment] 2020-10-29 19:25
If it's the build here - https://github.com/bjorn/tiled/releases/download/v1.4.2/Tiled-1.4.2-macos.zip - then I'm afraid that doens't work on macOS Big Sur beta 11.0.1 :( Same issue as before ...

**Comment by bjorn** [comment] 2020-10-29 19:26
@FahimF No, I meant the latest _snapshot_, which I published yesterday (version 2020.10.28), not the 1.4.2 release that was done a while ago.

**Comment by FahimF** [comment] 2020-10-29 19:30
@bjorn Yeah, I realized my mistake after I posted - should have checked the build date first :) And yes, can confirm the snapshot build works fine on macOS Big Sur beta 11.0.1

**Comment by bjorn** [comment] 2020-10-29 20:16
@FahimF Yeah! :partying_face:

**Closed by bjorn** 2020-10-29 20:16 UTC
Labels: bug, macos

**Comment by bjorn** [comment] 2020-11-16 22:14
Can somebody try whether the following release works on Big Sur?

[Tiled-1.4.3-macos.zip](https://github.com/bjorn/tiled/files/5550042/Tiled-1.4.3-macos.zip)

The main difference from the previous attempt is that it is built with Xcode 12 instead of 9.

**Comment by fahim-lookback** [comment] 2020-11-16 22:51
@bjorn Yep, works fine :)

**Comment by msanatan** [comment] 2020-11-17 03:31
I found this thread in good time! Another Mac user who just upgraded to Big Sur, latest version works great

**Comment by bjorn** [comment] 2020-11-17 08:14
Thanks all for testing, I'm going to release this today! 🎉

**Comment by v4ld3r5** [comment] 2020-11-22 16:17
> Can somebody try whether the following release works on Big Sur?
> 
> [Tiled-1.4.3-macos.zip](https://github.com/bjorn/tiled/files/5550042/Tiled-1.4.3-macos.zip)
> 
> The main difference from the previous attempt is that it is built with Xcode 12 instead of 9.

I confirm this is working for me as well, Big Sur 11.0.1
