### ISSUE TITLE
Wang tile coloring incorrect for isometric tiles of unusual dimensions

### ISSUE THREAD

**Issue by BorisTheBrave** [bjorn/tiled#2101] opened 2019-04-06 11:25 UTC
I have an isometric tileset with the following settings:

    <tileset tilewidth="64" tileheight="192" ...
      <grid orientation="isometric" width="64" height="32"/>

In other words, the tiles extend upwards a lot beyond the flat surface of the map. I tried to set up wang tiles for this tile set, but it looks like the editor is using tilewidth / tileheight to draw the colors, rather than width / height.

# Steps to reproduce

Download the tileset and accompanying image: [tileset.zip](https://github.com/bjorn/tiled/files/3050408/tileset.zip)

Open the tileset and add a wang set, and some colors. Hover or draw those colors anywhere over the tileset.

# Actual Behaviour
The colors are drawn on the inside of a rhombus with size 64 / 192. This causes graphical glitches as it extends outside the rectangular bounds of that tile, and anything drawn there isn't cleaned up when the mouse leaves the tile.

![image](https://user-images.githubusercontent.com/183773/55668767-0d9fdd80-5866-11e9-9fcb-1fa71a2256ba.png)

(the mouse is over the top middle tile in this image)

# Expected behaviour
The colors should be on the inside of a diamond with width 64 and height 32, like for a normal isometric tileset. The diamond should be oriented as it appears in the map editor, (i.e. respecting drawing offset). Additionally, there should be no graphical glitches when colors are drawn outside the bounds of the tile.

# Other details
Tiled v1.2.3. Windows 10 64 bit

NB: All graphics come from https://opengameart.org/content/medieval-building-tiles
They are licensed to Clint Bellanger under CC-BY-SA.

**Comment by bjorn** [comment] 2020-08-12 09:25
Can't reproduce on latest version anymore. Might have been a duplicate of #1943 which was fixed in 6c369e8a5c2fc3676346671a28f15ebc5bcc7b6c.

**Closed by bjorn** 2020-08-12 09:25 UTC
Labels: bug
