### ISSUE TITLE
Tile Sets don't always update image on Windows

### ISSUE THREAD

**Issue by Botanicula** [bjorn/tiled#2056] opened 2019-01-07 13:38 UTC
When I'm working on a map or a tile set, and I modify the source image of the Tile Set in an image editor and save it, it doesn't always update inside of Tiled, the first time or so it updates. I have to manually restart the program to see the new changes.
This only happens on Windows. On Mac the changes are always updated instantly.

**Comment by bjorn** [comment] 2019-01-08 20:54
Are you using Photoshop? If so this is a duplicate of issue #44.

In any case I really should give it another try to make this system more robust...

**Comment by Botanicula** [comment] 2019-01-08 21:16
Yes only tested with Photoshop. (Tested CC 2018 and lower). Alright! It works perfectly on Mac.

**Comment by bjorn** [comment] 2019-01-14 08:43
Alright, closing this issue as duplicate of #44.

**Closed by bjorn** 2019-01-14 08:43 UTC
Labels: bug
