### ISSUE TITLE
Tileset columns changed - Apply choice & ask once

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1786] opened 2017-10-17 20:15 UTC
When I press no, it keeps asking me this every single time i open the .tmx file.
Ask once and apply changes.

![image](https://user-images.githubusercontent.com/9143253/31687051-6ea8f8e8-b388-11e7-8cc2-6261ca910bc3.png)

**Comment by bjorn** [comment] 2017-10-17 20:31
Duplicate of issue #1770.

**Closed by bjorn** 2017-10-17 20:31 UTC
