### ISSUE TITLE
Add option to change backgroundcolor for tilelistboxes

### ISSUE THREAD

**Issue by botlin** [bjorn/tiled#1301] opened 2016-06-10 07:55 UTC
Lets say I create a Tileset from an image with tiles containing white or very bright pixels. Text overlays, snow, reflections for examples. Well then its hard to find the right tile in the tilelist,because the backgroundcolor is also white. The same problem happens in the animation window.
Would be good to be able to change the backgroundcolor of these menu  elements.
Best regards!

**Comment by bjorn** [comment] 2016-06-10 20:16
I'll look into this the next day I'm working on Tiled, since this is starting to become one of the most embarrassing missing features. I'll close this issue since it's a duplicate of #227.

**Closed by bjorn** 2016-06-10 20:16 UTC
