### ISSUE TITLE
Move placed tiles on the level

### ISSUE THREAD

**Issue by Deph0** [bjorn/tiled#1017] opened 2015-07-07 17:33 UTC
Hi, sorry if somebody requested this already-

Would be great if you could move a tile that is placed on the level already by selecting it, and maybe use a dedicated move tool to move the tile around on the level, this could probably also be used to move the tile around onto different layers. 

to rephrase:
select tiles, select move tool, drag the select tiles around.

also; select+backspace doesn't seem to delete the tiles? bug or just not implemented?

**Comment by kheftel** [comment] 2015-07-07 18:18
you can do this by selecting tiles, cut, paste, click where you want them moved to.

**Comment by Deph0** [comment] 2015-07-07 19:36
sure, but then I need to spend time removing the leftovers, which is time-consuming if moving a bunch of things.

**Comment by kheftel** [comment] 2015-07-07 19:49
Leftovers? Not sure what you mean.

**Comment by bjorn** [comment] 2015-07-07 19:50
> also; select+backspace doesn't seem to delete the tiles? bug or just not implemented?

You need to press Delete, not Backspace. It seems especially OS X users are more used to pressing Backspace, so I'll consider adding this as an option. On the other hand, I had other plans for "Backspace", for example to go one step back while drawing a polygon/polyline.

**Comment by Deph0** [comment] 2015-07-07 19:53
fn+backspace would be equal to delete on a mac keyboard, which doesn’t do it either.

**Comment by kheftel** [comment] 2015-07-07 20:01
I have two keys on my Mac keyboard marked delete, one has an arrow pointing right and is where del would be on a pc keyboard, one is where the backspace key would be on a pc keyboard.  Neither work, with or without combinations of fn, shift, cmd, alt, ctrl,etc....

Also, don't know if it's relevant but no keyboard shortcut shows up in the menu:
![image](https://cloud.githubusercontent.com/assets/669328/8555920/967c8740-24b0-11e5-8c84-a23132ec7a79.png)

I'm on OSX 10.10.3, tiled 0.12.0

**Comment by bjorn** [comment] 2015-09-26 15:10
I realized this is a duplicate of issue #650.

**Closed by bjorn** 2015-09-26 15:10 UTC
Labels: Feature
