### ISSUE TITLE
Terrain Brush on Edge of Map (When using Ctrl)

### ISSUE THREAD

**Issue by tderensis** [bjorn/tiled#458] opened 2013-06-11 22:16 UTC
When using the terrain brush along the right or bottom edge of the map and pressing CTRL (to make the brush smaller), clicking and holding to place a terrain along the edge does not work. If you try to draw along the edge two tiles are drawn and then the click is released and drawing stops until you click again. Therefore, the only way to draw along the right and bottom edges with the terrain brush is to click one by one.

**Comment by bjorn** [comment] 2016-04-24 13:59
I can't reproduce this anymore with Tiled 0.16. I think it was probably fixed by the changes in 0cd1368f3827d133505556a99268e4cb833d948b.

**Closed by bjorn** 2016-04-24 13:59 UTC
Labels: Bug
