### ISSUE TITLE
Tiled Collision Editor not working

### ISSUE THREAD

**Issue by Ultrachessmaster** [bjorn/tiled#846] opened 2014-12-21 07:17 UTC
I can't click and edit the collision of the tile on the Tiled Collision Editor. I click, but nothing happens. This is strange because I was able to edit the tileset before, with out a problem. I've researched all over the place but can't find an answer. Please help me figure this out.

**Comment by bjorn** [comment] 2015-09-14 12:42
I'll close this as duplicate of #242.

**Closed by bjorn** 2015-09-14 12:42 UTC

**Comment by craig1971** [comment] 2016-03-13 07:06
Can someone please explain this to me?

I have 2 separate maps that are both using an external tileset which contains collider masks that I created while in one of the maps, exported then imported into the second map.  Now i need to edit the collisions on some of my tiles.  I cannot seem to do this with either map loaded.

I have tried this:
"If you are using an External TileSet, you must first import it, make the changes you want to the collision, then export it again." - by opening my primary map, importing my colliders.tsx (i now have 2 instances in my Tileset window) then going to view > tile collision editor.  none of the collider tools work.  what am i doing wrong???  Thanks

**Comment by bjorn** [comment] 2016-12-12 22:21
@craig1971 This issue is resolved in the latest snapshot builds. If you're still editing external tilesets sometimes, please give the snapshots a try. If you have any feedback you can leave it at issue #242.
