### ISSUE TITLE
UI bug: dragging tileset order cause terrain list pointing to incorrect tileset

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1235] opened 2016-03-22 06:53 UTC
Step to reproduce:
- add a tileset
- setup a terrain type, which will be display in the terrain list view
- add another tileset
- now drag the second tileset to the front of first tileset in the tileset view
- terrain view will update and point to the second tileset (now first in the tileset list), which will be empty.

Save the map and relaunch tiled, the issue disappears. So the data is correct.

Tested ox OSX, not sure this is related to number of tilesets or not.

**Comment by bjorn** [comment] 2016-10-25 12:25
Unless there is another way to reproduce this, this issue will go away once `wip/tilesetdocument` is merged, since manual reordering of the tilesets is no longer possible (change 6bd6630e3f5e7fba8ed46bb478a4d0328e73a9b7).

**Comment by bjorn** [comment] 2017-02-13 07:22
Closing this since `wip/tilesetdocument` was merged.

**Closed by bjorn** 2017-02-13 07:22 UTC
Labels: Bug
