### ISSUE TITLE
Export custom object properties

### ISSUE THREAD

**Issue by EskelCz** [bjorn/tiled#1356] opened 2016-09-11 21:02 UTC
Hi. I'm wondering why are my custom properties for objects not showing in a json export file. I've read the manual for custom properties and there is no mention they are not meant for export. If so, why is that? What is the point of having editing of properties and property sets when the data stays in the editor?
Are we supposed to import and parse another file (xml) with these properties alone? This feels like a lot of effort for a common use case of the feature. Am I missing something?
Thank you for consideration or clarification.

**Comment by bjorn** [comment] 2016-09-12 07:10
I'll consider this a duplicate of #1313. Please see the discussion there for the rationale and feel free to leave a comment if you have other suggestions.

**Closed by bjorn** 2016-09-12 07:10 UTC
