### ISSUE TITLE
Anchor point for tile objects differs from shape objects

### ISSUE THREAD

**Issue by nrj** [bjorn/tiled#1579] opened 2017-05-25 17:38 UTC
This may be by design, but I didn't see it mentioned anywhere in the docs.

It appears that when inserting a Tile _object_ it's anchor point differs from that of rectangles and ellipses. Please see the image below in which all objects are set to position 0, 0.

<img width="496" alt="object-origins" src="https://cloud.githubusercontent.com/assets/149472/26462415/fbeae8c6-4180-11e7-8cb7-cb677b43ec84.png">

As you can see the anchor point for tile objects is the bottom left, whereas every other object type is top left.

**Comment by bjorn** [comment] 2017-05-25 21:06
This is a duplicate of #91.

It is indeed an annoying inconsistency, and I'd like to fix it eventually but it'll require making the object origin configurable. There is another aspect to this which is that the origin of tile objects on isometric maps is the bottom-center rather than the bottom-left.

The documentation does mention it but it's a bit hidden, from the [TMX Map Format](http://doc.mapeditor.org/reference/tmx-map-format/) page:

> "When the object has a gid set, then it is represented by the image of the tile with that global ID. The image alignment currently depends on the map orientation. In orthogonal orientation it's aligned to the bottom-left while in isometric it's aligned to the bottom-center."

**Closed by bjorn** 2017-05-25 21:06 UTC
