### ISSUE TITLE
Stamp Brush leaves a trace at moving camera

### ISSUE THREAD

**Issue by EFLFE** [bjorn/tiled#1374] opened 2016-10-10 11:22 UTC
Sample (on Windows 7 x64):

![sample](http://i.imgur.com/RTqAreX.gif)

Probably it was already a topic on this issue, but I have not found an answer.

**Comment by bjorn** [comment] 2016-10-25 11:58
Yes, this is a very annoying and long-standing issue. I'll close it as a duplicate of #174.

Probably, the best way to try to solve this would be to see if the issue is reproducible with a small QGraphicsView based example. If it isn't, then there must be something wrong in Tiled. And if it is, then we can report a proper bug against the Qt framework.

**Closed by bjorn** 2016-10-25 11:58 UTC
Labels: Bug
