### ISSUE TITLE
Really confused about polygon vertices inside JSON

### ISSUE THREAD

**Issue by BobarTrump** [bjorn/tiled#1853] opened 2018-01-08 09:45 UTC
Hi,

It' looks like a bug, but it seems a bit big and I first assume that I haven't understood something properly.

I have the following polygon : 
![probleme tileset](https://user-images.githubusercontent.com/24197355/34665151-70f39b5e-f45f-11e7-950f-e2b675d6afe4.png)

And here is the data I get in the JSON file I export : 
0 : {x: 15.0222, y: 542.2444}
1 : {x: 78.9843, y: 510.0156}
2 : {x: 79.0055, y: 574.0083}
3 : {x: 15         , y: 574}

x: 1
y: 34

My tiles are 64 x 64, I don't understand why I'm getting that > 500 value for "y". I don't get that offset at x too.

Also, the offsets for the tile at left are different : 
![probleme tileset 2](https://user-images.githubusercontent.com/24197355/34666109-f9c5c68e-f462-11e7-874e-d5f62f140db9.png)

0 : {x: 14.875, y: 186.03125}
1 : {x: 79, y: 153.84375}
2 : {x: 78.96875, y: 186}

x: 7.5
y: 61

**Comment by bjorn** [comment] 2018-01-08 10:16
Hmm, I don't understand this either and I can't reproduce this problem in a quick test. Maybe you can share your files so I can look into it further?

**Comment by BobarTrump** [comment] 2018-01-08 10:21
Here it is : 

[TiledPolygonProblem (2).zip](https://github.com/bjorn/tiled/files/1611183/TiledPolygonProblem.2.zip)

**Comment by bjorn** [comment] 2018-01-08 10:34
Hmm, I don't see the problem in the TMX file, nor in the JSON export. How exactly are you causing this issue? Maybe you could attach the strange JSON export you're getting as well?

**Comment by BobarTrump** [comment] 2018-01-08 10:49
yes, my bad it doesn't comes from the JSON export, I was looking its value through the Chrome Console and it's seems that the bug comes from there, stills really weird,  sorry :/

**Comment by bjorn** [comment] 2018-01-08 10:53
Alright, no problem. I'll close this issue, but if you do track it down I'm curious to hear how it was caused. :-)

**Closed by bjorn** 2018-01-08 10:53 UTC

**Comment by bjorn** [comment] 2018-01-12 09:31
I just noticed while looking at this tileset that the tiles are actually 128x128.
