### ISSUE TITLE
Teamviewer QuickConnect button crash

### ISSUE THREAD

**Issue by Yanrishatum** [bjorn/tiled#1317] opened 2016-07-19 06:42 UTC
When teamviewer starts, it automatically adds QuickConnect button to every window, including already running Tiled instance, resulting in Tiled not responding.
Version: 0.16.1
OS: Windows 7 (Classic theme)
Step to reproduce:
1. Start tiled.
2. Start teamviewer with QuickConnect button enabled (it is by default, and can be disabled only via advanced options)

**Comment by bjorn** [comment] 2016-07-21 20:47
That is annoying, but I heavily doubt I could do anything about this in Tiled. Tiled 0.16.1 was built against Qt 5.5, so some questions:

* Do all Qt applications stop responding as a result of starting teamviewer? (You could check with applications like [Quassel](http://quassel-irc.org/), [Krita](http://krita.org/), [TexturePacker](https://www.codeandweb.com/texturepacker) or [Telegram Desktop](https://desktop.telegram.org/)).
* Does Tiled 0.16.2, built against Qt 5.6, still show this problem?

**Comment by Yanrishatum** [comment] 2016-07-22 01:33
1. Telegram reacting fine to Teamviewer. Krita 3.0.0 too.
2. 0.16.2 - problem still present.
3. After some testing found out that if you turn off OpenGL rendering - problem disappears. GLContext lost when that button added? So, new reproduction step is:
0. Turn on OpenGL rendering.

**Comment by bjorn** [comment] 2016-07-22 06:48
Ok, thanks for testing. That's still a Qt issue though, but maybe it would be resolved by switching from `QGLWidget` to the new `QOpenGLWidget`. That's a change I will look into pushing to a test branch.

**Comment by bjorn** [comment] 2016-12-14 08:04
@Yanrishatum The [latest snapshots](https://update.mapeditor.org/snapshots-win/) are using `QOpenGLWidget` instead of `GLWidget`. Could you try whether this avoids this crash?

**Comment by Yanrishatum** [comment] 2016-12-14 12:23
Nope, still hangs. http://wb.yanrishatum.ru/dump/s161214151833.png
As well tested with Aero theme enabled (considering recent discovery that "desktop" discord programmed so bad, it's notifications don't work on non-aero theme) - same result, hangs app.

Also render's a bit broken with snapshot on startup and OGL enabled: http://wb.yanrishatum.ru/dump/s161214152008.png (repaint fixes it)

**Comment by bjorn** [comment] 2016-12-14 12:25
Oh well, thanks for testing!

**Comment by bjorn** [comment] 2019-05-07 21:03
@Yanrishatum Are you still experiencing this hang with current Tiled, which is compiled against Qt 5.9?

If not... tomorrow I expect to push a new development snapshot built against Qt 5.12... maybe the issue is finally gone then!

**Comment by Yanrishatum** [comment] 2019-05-08 00:34
Sadly, I no loner have the reproduction prerequisites (Migrated to Win10) and on top of that, latest teamviewer does not even have the QuickConnect feature (Since TV13), so I would say it's safe to close this issue, as the culprit no longer contains the feature that causes the crash (And they are pretty adamant on keeping TV instances up to date, otherwise it refuses to connect).

**Comment by bjorn** [comment] 2019-05-08 07:29
@Yanrishatum Ah, no need to be sad. Sometimes issues just disappear if you wait long enough. Let's be happy that we can close this one!

**Closed by bjorn** 2019-05-08 07:29 UTC
Labels: bug, qt issue, windows
