### ISSUE TITLE
Allow scrolling past the boundaries of the map

### ISSUE THREAD

**Issue by rparkes** [bjorn/tiled#1102] opened 2015-09-28 22:24 UTC
For example, in the following image, I would like to be able to scroll past the bottom right corner of the map to make it easier to work with.

![Bottom-right Corner](http://i.imgur.com/LZGe5H9.png)

**Comment by bjorn** [comment] 2015-09-29 07:45
Duplicate of  #245.

I agree of course, and have scheduled the existing issue for Tiled 1.0 now.

**Closed by bjorn** 2015-09-29 07:45 UTC
