### ISSUE TITLE
Tiled does not indicate the need to re-save maps that depend on an external tileset that has changed.

### ISSUE THREAD

**Issue by Koraken** [bjorn/tiled#1961] opened 2018-06-19 02:52 UTC
Reproduction: The issue can be reproduced with having multiple maps, each of which using more than one tileset and depending on at least one that is the same. Add a tile to a tileset that multiple maps depend on. The firstgid's of the maps now no longer match up with the length of the tileset, breaking the maps until they are re-saved.

Expectation: Tiled would indicate that there has been a change in the external tileset that now breaks the maps until they are saved again.

Reality: Tiled does not make the indication.

Got caught in a little frustrating rabbit hole when all of my maps broke after a tileset change. Maybe it would be obvious to some, but an indication that the maps need to be re-saved because of an external tileset change would be nice. Even just a little '*' like with other changes.

**Comment by bjorn** [comment] 2018-06-19 08:37
In which way did your maps "break"?

Adding a tile to an external tileset does not generally require maps using that tileset to be re-saved, because the new tile gets a new ID that is not referenced by those maps. If this causes the map to fail to load correctly, then there is a bug in the loader.

**Comment by Koraken** [comment] 2018-06-19 23:38
In my specific instance I had two tilesets in my maps. One called 'objects', that had 4 tiles, and one called 'city' which had many tiles.  

The map file had the lines: 
` <tileset firstgid="1" source="tilesets/objects.tsx"/>`
` <tileset firstgid="5" source="tilesets/city.tsx"/>`

At this point, GID 5 refers to the first tile in city.

I open the objects tileset in Tiled and added a tile. The map file is unchanged. 

Now GID 5 refers to the last tile in objects, the map breaks in the sense that all GID 5 tiles are now something different.

After re-saving the map, the lines changed:
` <tileset firstgid="1" source="tilesets/objects.tsx"/>`
` <tileset firstgid="6" source="tilesets/city.tsx"/>`
and everywhere that referenced GID 5 now correctly references GID 6.

In hindsight I would expect that the map would need to be resaved after the tileset it refers to changes, but Tiled didn't give any indication that it was necessary, which is the target of this issue.

I may very well be missing something of course!

**Comment by bjorn** [comment] 2018-06-19 23:42
> Now GID 5 refers to the last tile in objects, the map breaks in the sense that all GID 5 tiles are now something different.

Well, GID 5 does not refer to the last tile in objects, because `city.tsx` was assigned `firstgid` of 5, so `objects.tsx` is no longer relevant starting from global tile ID 5. The map should load fine in Tiled, unless I've introduced a bug. Could it be that the map loader you're using is not mapping the global IDs to local in the correct way?

**Comment by bjorn** [comment] 2018-07-19 15:12
Closing issue, since the problem is in a map loader that is not part of Tiled.

**Closed by bjorn** 2018-07-19 15:12 UTC
