### ISSUE TITLE
Help trying to build latest tiled on Debian 9 with Python 3 support

### ISSUE THREAD

**Issue by ProtossGP32** [bjorn/tiled#2137] opened 2019-06-10 09:04 UTC
Hi there!
First of all I'd like to congrat @bjorn for this awesom tool! Some of my colleagues have been using it for serveral years now and they all say it's a must and the first app to install on their game development environment.

I would like to create some python scripts to custom export tiled projects to a convenient format, but the first issue I came across was the python plugin availability. Every time I try to build tiled it seems to ignore the python support:
![image](https://user-images.githubusercontent.com/19353116/59183819-11edbd00-8b6d-11e9-8de3-f4357b41db1a.png)

Here's some info that could be useful:
```
protoss@debian-pc:~$ tiled --version
Tiled 1.2.4

protoss@debian-pc:~$ python3 --version
Python 3.5.3

protoss@debian-pc:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
The build was done following the guide on the main page, without changing any default parameter, just executing the qmake and make.

Following issue #1900 I've also tried to modify [src/plugins/python/python.qbs](https://github.com/bjorn/tiled/pull/1900/files/eab63011e18464c64f8f9f29ac87d0fdcf6686c2#diff-fb4744a9de5eb49bfce1cb732fbacca6) to adapt it to Python-3.5, but it has been unsuccessful.

I'd much appreciate your help on this matter, I can't wait to get my hands on this feature!

**Comment by bjorn** [comment] 2019-06-10 10:24
> The build was done following the guide on the main page, without changing any default parameter, just executing the qmake and make.
> 
> Following issue #1900 I've also tried to modify [src/plugins/python/python.qbs](https://github.com/bjorn/tiled/pull/1900/files/eab63011e18464c64f8f9f29ac87d0fdcf6686c2#diff-fb4744a9de5eb49bfce1cb732fbacca6) to adapt it to Python-3.5, but it has been unsuccessful.

With the upgrade to Python 3, the qmake support for building the Python plugin was dropped. There should be no adaptions needed for Python 3.5, but you need to build with Qbs instead of qmake. I'm sorry that this isn't made clear anywhere (I hope to remove all the qmake files soon).

Btw, I understand you're very excited about Python scripting, but would JavaScript be an alternative for you as well? I'm working on making Tiled fully scriptable using JavaScript, which is what the "Extensions" mentioned in your screenshot are about. Apart from extending Tiled with custom actions or custom tools, you can also [add custom export formats using JavaScript](https://doc.mapeditor.org/en/latest/reference/scripting/#script-registermapformat), though right now only text-based formats are supported (binary support coming soon).

**Comment by ProtossGP32** [comment] 2019-06-10 12:23
Hi Bjorn, thanks for the quick reply!

Okey, so I should build with Qbs. Could you give me some quick hints on how to build it this way? Thuth is, I'm pretty noob at compiling source code and don't know a thing out of a given Makefile.

Regargind JavaScript, that's a language I've never used before, apart from defining one or two functions for a minimum webserver, so I didn't think of it as an option. However, some of my colleagues do use it on a daily basis, so they will sure welcome this feature!

**Comment by bjorn** [comment] 2019-06-10 14:00
> Okey, so I should build with Qbs. Could you give me some quick hints on how to build it this way? Thuth is, I'm pretty noob at compiling source code and don't know a thing out of a given Makefile.

Actually I made a mistake. I had already removed all .pro files in my local checkout and forgot this when I checked whether the Python plugin could be built with qmake. There appears to be a `python.pro` and I think it should work on Linux provided Python can be found using pkgconfig. On Debian this probably means [you need to have the `python3-dev` package installed](https://packages.debian.org/stretch/amd64/python3-dev/filelist).

I guess it's easier to make sure you've got that installed than me explaining how to use Qbs. I'll try to find some time to update the README.md to mention Qbs soon.

The JavaScript feature is already available on `master` and in the development snapshots, so if that's a solution as well please do give it a try. Any feedback would really help shape up Tiled 1.3.

**Comment by ProtossGP32** [comment] 2019-06-10 14:28
I did have installed the `python3-dev` package prior to building Tiled. Just did it after reading your comment here [again on #1900 ](https://github.com/bjorn/tiled/pull/1900#issuecomment-372811000).
```
apt list --installed | grep python3-dev

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpython3-dev/stable,now 3.5.3-1 amd64 [instal·lat,automàtic]
python3-dev/stable,now 3.5.3-1 amd64 [instal·lat]
```

So is there anything else I could do to debug this issue?

**Comment by bjorn** [comment] 2019-06-11 14:18
The qmake project does the following to locate Python:
```qmake
    unix {
        packagesExist(python3) {
            HAVE_PYTHON = yes
            CONFIG += link_pkgconfig
            PKGCONFIG += python3
        }
    }
```
And the `plugins.pro` file does:
```
contains(HAVE_PYTHON, yes) {
    message("Have Python, will slither")
    SUBDIRS += python
} else {
    !build_pass:message("No Python support")
}
```
So, when running `qmake`, one of these messages should appear to let you know whether the Python plugin is enabled at all. You will need to run `qmake -r` (recursive) for qmake to adapt to any changes you have made to your system regarding the Python detection.

If you get the "No Python support" message, you can try to manually run the following command to see what the problem may be:
```sh
pkg-config --modversion python3
```
It should print 3.5 in your case. If it does, then I would have no idea why the Python plugin would get disabled for the qmake build.

**Comment by ProtossGP32** [comment] 2019-06-11 17:59
Thanks again for your quick reply! I proceed to share a results log of the process with your last suggestion:

**Comment by ProtossGP32** [comment] 2019-06-11 18:33
Thanks again for your quick reply! I proceed to share a report log of my latest attempt to build Tiled with your last suggestions:
• I cloned again to an empty folder the Tiled Git repo
• Launched `qmake -r`: the results are as expected, python is found:
```
$ qmake -r
Info: creating stash file /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/.qmake.stash
Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/src.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/libtiled/libtiled.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/tiled/tiled.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/plugins.pro
Project MESSAGE: Have Python, will slither
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/csv/csv.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/defold/defold.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/droidcraft/droidcraft.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/flare/flare.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/gmx/gmx.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/json/json.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/json1/json1.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/lua/lua.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/replicaisland/replicaisland.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/tbin/tbin.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/tengine/tengine.pro
  Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/plugins/python/python.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/tmxviewer/tmxviewer.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/tmxrasterizer/tmxrasterizer.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/automappingconverter/automappingconverter.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/terraingenerator/terraingenerator.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/tiledquickplugin/tiledquickplugin.pro
 Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/src/tiledquick/tiledquick.pro
Reading /media/protoss/Dades/_debian_unit/Programes/Disseny/tiled/translations/translations.pro
```
• Launched `make`: It is still at it; I'll come back with the report once it has finished, but I wanted to inform you that I'm trying your suggestions again.

**Comment by bjorn** [comment] 2019-06-11 20:19
> Thanks again for the constant feedback, apart from these errors related to the thumbnail and other file formats, it seems to work just fine. Time to work on some Python scripts!

The errors appear to be caused by attempts to run the `strip` tool on stuff that it doesn't support (it's supposed to only be used to strip unnecessary data out of binaries). I haven't seen that before and don't know what would cause this.

If you have any idea why it didn't work before I'd be interested to hear about it. In any case I'm glad we can close this issue now! :-)

And please do keep in mind that in the next Tiled feature release I intend to fully support JavaScript for scripting many things in Tiled, including custom map formats, so even if you have more experience in Python in may be worth to try out doing it in JavaScript as well.

**Closed by bjorn** 2019-06-11 20:19 UTC

**Comment by bjorn** [comment] 2019-06-11 20:25
> aunched `Tiled`, now available from the Applications Menu (but without thumbnail, I suppose it's related to the prior errors):

Ah, just thought I'd mention, those errors are likely not related to the icon not showing up. That's probably due to installing Tiled in `/usr/local`, so the icon ended up in `/usr/local/share/icons/hicolor/32x32/apps/`, which may not be a location that is searched by your applications menu (though evidently the .desktop file in `/usr/local/share/applications/` was found). So that problem would likely go away if you picked `/usr` as the prefix rather than `/usr/local` (see section about installing in the `README.md`).

**Comment by ProtossGP32** [comment] 2019-06-11 21:37
> If you have any idea why it didn't work before I'd be interested to hear about it. In any case I'm glad we can close this issue now! :-)
> 
> And please do keep in mind that in the next Tiled feature release I intend to fully support JavaScript for scripting many things in Tiled, including custom map formats, so even if you have more experience in Python in may be worth to try out doing it in JavaScript as well.

I think the main difference was that on my first attempt I didn't use the `-r` flag when launching `qmake`. If you read again the `README.md`, the `-r` flag only appears on the section when you suggest how to change the installation path, thus making me thing this was an optional flag when it seems compulsory for the correct python detection). If that's true, you should change the `README.md` to always use that flag with `qmake`.

**Comment by bjorn** [comment] 2019-06-12 07:00
Hmm, if the `-r` fixed it, then it's because something changed in your environment after you had run qmake for the first time. At that point all the Makefiles are already generated, and it's not going to recursively re-generate them unless you explicitly tell it to.

I could reword the `README.md` to speak more generally than just talking about the case of changing the installation path, though really it should be rewritten with Qbs instructions.
