### ISSUE TITLE
Problems launching Tiled in MacOS 'Sur'

### ISSUE THREAD

**Issue by breakintoprogram** [bjorn/tiled#2936] opened 2020-11-13 13:01 UTC
After upgrading to Sur...
Tiled version 1.4.2
The application launches, briefly displays its menu items, then that's it...
Error log attached.
Worked fine previously in Catalina.
[error_report.rtf.zip](https://github.com/bjorn/tiled/files/5536857/error_report.rtf.zip)

**Comment by AZbang** [comment] 2020-11-13 13:41
+1

**Comment by AZbang** [comment] 2020-11-13 13:59
This solves the problem for me:
sudo nano /etc/hosts -> 127.0.0.1 http://ocsp.apple.com

**Comment by bjorn** [comment] 2020-11-13 14:26
@AZbang Wow, that sounds weird. Any source for this solution?

@breakintoprogram The next release will work on Big Sur, but in the meantime you can use the development snapshots. The latest snapshot version at https://thorbjorn.itch.io/tiled is 2020.10.30 at the moment and it should work fine.

**Comment by bjorn** [comment] 2020-11-13 14:28
Closing as duplicate of #2845.

**Closed by bjorn** 2020-11-13 14:28 UTC

**Comment by AZbang** [comment] 2020-11-13 17:52
@bjorn https://twitter.com/stauffermatt/status/1326996782665052162

**Comment by breakintoprogram** [comment] 2020-11-13 19:05
@bjorn Thank you, much appreciated. I'll check the development snapshot out later.

**Comment by bjorn** [comment] 2020-11-13 19:05
@AZbang Ah, thanks. Yeah, could have been the problem here, though Tiled 1.4 is also having other issues on Big Sur.
