### ISSUE TITLE
Offset Map command should move objects (not clone them)

### ISSUE THREAD

**Issue by giuseppelt** [bjorn/tiled#1290] opened 2016-06-01 11:34 UTC
Usually I link objects by their id, for instance, one object has a property `childOf` with the Id of another object.

And when I use the **offset map** command to shift tiles/objs, all links break because objects are shifted visually (so coords are ok), but all ids are changed. It seems, the command clones all objects to the new coords and delete originals.

I often use offset map command, and everytime I have to manually update each property with new ids.

**Comment by bjorn** [comment] 2016-06-01 11:37
That's a bug, thanks for pointing it out! Of course the offsetting should have no effect on the IDs.

The cloning just made it easier to keep the undo history. I'll either have to make sure the cloning also clones the IDs, or change the implementation to use a move command.

**Comment by bjorn** [comment] 2016-06-12 10:32
Which version of Tiled are you using? I could not reproduce this issue, and I think it was actually recently fixed in change 4bc108a837ea48b16bed2d09cb0d0358a056f0ce, which is included in Tiled 0.16.1. So if you're using Tiled 0.16.0 or older, please try to upgrade and let me know if you still have this issue.

**Comment by giuseppelt** [comment] 2016-06-12 10:43
I'm using 0.15.1. I'll try to upgrade, and let you know.
________________________________
Da: Thorbjørn Lindeijer<mailto:notifications@github.com>
Inviato: ‎12/‎06/‎2016 12:32
A: bjorn/tiled<mailto:tiled@noreply.github.com>
Cc: giuseppelt<mailto:giuseppelt@live.com>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [bjorn/tiled] Offset Map command should move objects (not clone them) (#1290)

Which version of Tiled are you using? I could not reproduce this issue, and I think it was actually recently fixed in change 4bc108a837ea48b16bed2d09cb0d0358a056f0ce, which is included in Tiled 0.16.1. So if you're using Tiled 0.16.0 or older, please try to upgrade and let me know if you still have this issue.

---

**Comment by bjorn** [comment] 2016-06-16 22:04
I'll close this because I'm quite confident it is fixed. Please let me know when you notice it's still there in version 0.16.1 or newer.

**Closed by bjorn** 2016-06-16 22:04 UTC
Labels: Bug, Urgent
