### ISSUE TITLE
Tiled stops reloading images when editing them via Photoshop

### ISSUE THREAD

**Issue by pkmnfrk** [bjorn/tiled#2024] opened 2018-10-12 21:57 UTC
Tiled Version: 2018.09.12
Platform: Windows 10 64bit
Photoshop version: CC 2018 (19.1.4)

Problem:
-

Tiled sometimes fails to reload a modified image. Usually (potentially always), this is when said image is being edited in Photoshop.

Steps to reproduce:
-

1. Assume a tileset referencing `image.png`, open in Tiled
2. Open `image.png` in Photoshop
3. Make a change, and save `image.png` (just using the normal Save, not Export)
4. Observe Tiled, it will have reloaded
5. Make another change, and save again

Expected:
-

Tiled reloads the image

Actual:
-

Tiled no longer reloads the image, even when editing them with other programs (eg, Paint). Requires a restart of Tiled to start reloading again

Note:
-

Windows Explorer notices the changes every time. Editing with other applications than Photoshop does not trigger this behaviour (ie, it reloads every time)

Baseless conjecture:
-

Perhaps something that Photoshop is doing during a Save confuses Tiled, and causes it to go into a state where the reloading never finishes and therefore doesn't try and reload in the future?

**Comment by bjorn** [comment] 2018-10-13 20:15
Thanks for the detailed bug report! However, I'll close it since it is a duplicate of issue #44.

I had hoped this issue would be resolved by change 2358419d25ca5d89eb68fca12499d3e1ebb8977e, but it failed to address the issue. :-(

**Closed by bjorn** 2018-10-13 20:15 UTC
