### ISSUE TITLE
Tiled crashes when it cannot use Hardware accelerated drawing OpenGL

### ISSUE THREAD

**Issue by DrMefistO** [bjorn/tiled#1085] opened 2015-09-15 11:23 UTC
My video card drivers cannot use OpenGL.
When I'm trying to open tmx file, Tiled crashes. But with uncheched acceleration mode, it draws everything and works good.
Can it be fixed?

**Comment by bjorn** [comment] 2015-09-15 12:23
I'm not sure how I could avoid these kind of crashes unfortunately, because they are not triggered by code in Tiled, but generally by some low-level Qt code or possibly even Windows / driver code.

If you have trouble starting Tiled again because it tries to use OpenGL, you can start it with the `--disable-opengl` command line parameter.

**Comment by bjorn** [comment] 2015-09-15 12:26
I've labeled this Windows, please correct me if I'm wrong.

Note that there is virtually no advantage to using accelerated drawing. In general Tiled is perfectly fast when using software rendering.

**Comment by DrMefistO** [comment] 2015-09-15 12:41
Yep, this is Windows bug. This problem exists, because, by some reason, OpenGL mode was enabled by default on my system.

**Comment by bjorn** [comment] 2015-09-15 12:59
Hmm, OpenGL rendering is disabled by default on all systems because of these reliability problems. It could be that it was enabled by default in an old version.

**Comment by bjorn** [comment] 2015-09-15 14:06
I'm closing this because it's a duplicate of issue #525.

**Closed by bjorn** 2015-09-15 14:06 UTC
Labels: Bug, Windows
