### ISSUE TITLE
itch.io downloads are mislabeled

### ISSUE THREAD

**Issue by nureyev** [bjorn/tiled#1287] opened 2016-05-28 21:04 UTC
The Windows 32-bit link downloads the win64.msi, while the Windows 64-bit link downloads the osx.dmg and so on.

**Comment by bjorn** [comment] 2016-05-29 14:17
Thanks for reporting! Unfortunately, I was away for a few days... closing this as duplicate of #1287.

**Closed by bjorn** 2016-05-29 14:17 UTC
