### ISSUE TITLE
Fail to install Tiled on Ubuntu 14.04

### ISSUE THREAD

**Issue by Murii** [bjorn/tiled#1000] opened 2015-06-24 14:49 UTC
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tiled : Depends: libqt4-opengl (>= 4:4.5.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Ablu** [comment] 2015-06-24 17:11
I cannot reproduce this issue in a docker environment. How are you installing tiled? From the PPA?

What happens if you try to install libqt4-opengl manually? This looks a bit like your system packages are in an inconsistent state.

**Comment by Murii** [comment] 2015-06-25 07:22
I'm installing Tiled by doing: sudo apt-get install Tiled.
When I want to install libqt4-opengl I get :
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqt4-opengl : Depends: libqtcore4 (=
4:4.8.5+git192-g085f851+dfsg-2ubuntu4+elementary3+r1~ubuntu0.3.1) but
4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1 is to be installed
                 Depends: libqtgui4 (=
4:4.8.5+git192-g085f851+dfsg-2ubuntu4+elementary3+r1~ubuntu0.3.1) but
4:4.8.5+git192-g085f851+dfsg-2ubuntu4.1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Ablu** [comment] 2015-06-25 07:36
It looks like your systems has a mixed set of ubuntu and elementary packages. One does not seem to satisfy the other, which results in a broken package state for you. Looks like you need to remove the elementary packages and install the ubuntu ones.

**Comment by Murii** [comment] 2015-06-25 11:00
God damn Elementary !

**Comment by bjorn** [comment] 2015-06-25 21:19
First of all, congratulations! You've reported the 1000th issue for the Tiled project! But unfortunately there is no reward for this achievement.

Now I'm closing this, since it's not an issue with Tiled. :-)

**Closed by bjorn** 2015-06-25 21:19 UTC
