### ISSUE TITLE
Object type field bugs out if custom properties are set

### ISSUE THREAD

**Issue by aeonofdiscord** [bjorn/tiled#1295] opened 2016-06-05 16:01 UTC
Just had this problem: if I create an object and set a custom property on it, I can't then edit the 'type' field without the edit box losing focus after one or two characters.

**Comment by bjorn** [comment] 2016-06-05 16:02
Is this a duplicate of issue #1244?

**Comment by aeonofdiscord** [comment] 2016-06-05 16:06
...yes.

**Closed** 2016-06-05 20:01 UTC
