### ISSUE TITLE
Native Map Resizing

### ISSUE THREAD

**Issue by windmarble** [bjorn/tiled#449] opened 2013-06-04 16:52 UTC
I would like to be able to adjust the tile size natively when resizing a map. So I can make a HD version and SD version of the same map without using 3rd party tools.

**Comment by bjorn** [comment] 2015-10-10 12:36
I'll close this issue because I don't think there's much Tiled can do here.

The problem is really just about loading higher resolution textures on larger screens (or lower resolution on smaller screens) and this is outside the scope of Tiled. It can be implemented purely on the game size, using for example a custom property to tell it which alternative images to use. Often a special naming convention is used for this which even makes such properties unnecessary.

**Closed by bjorn** 2015-10-10 12:36 UTC
