### ISSUE TITLE
Windows 10 Crash on Startup

### ISSUE THREAD

**Issue by atbigelow** [bjorn/tiled#1129] opened 2015-10-19 02:15 UTC
Haven't needed to try Tiled out since updating to W10. I updated to v0.14.2 and get an immediate "tiled.exe has stopped working." I tried various daily builds of both 32 and 64 bit versions back to Aug24th without being able to get any of them to work.

I can see, based on my Tiled map history that is still intact, that it is able to load the tileset and display properly but the mapview is highly distorted.

0.13.1 worked prior to be updating. But now I can't seem to rollback to it; I get the same crash.

**Comment by bjorn** [comment] 2015-10-19 07:20
Maybe you enabled OpenGL rendering? Please try starting Tiled with the `--disable-opengl` command line parameter.

**Comment by atbigelow** [comment] 2015-10-19 14:17
That was definitely it! Did older Tiled versions not use it but it became default, so it switched up my configs? Just wondering how to prevent this for others.

**Comment by bjorn** [comment] 2015-10-19 14:21
Right now you just have to avoid checking that box. It has been disabled by default for a long time. I don't know how I could stop it from crashing (it's a bug in Qt), but I should make recovery easier somehow.

In any case I'll close this as duplicate of #525 then.

**Closed by bjorn** 2015-10-19 14:21 UTC
Labels: Bug, Windows
