### ISSUE TITLE
Object in (0,0) but x/y positions differ

### ISSUE THREAD

**Issue by spectre-hydra** [bjorn/tiled#1916] opened 2018-03-27 12:30 UTC
![image](https://user-images.githubusercontent.com/33549831/37967319-4ce11d1e-31cb-11e8-88e2-95fa91c58962.png)

There's an object on a (0,0) tile, but it gets a position (0, 512), like it was on (0,1).

What do we do with that?

Windows10 64bit

**Comment by bjorn** [comment] 2018-03-27 12:50
Duplicate of #91. See the discussion there about the reason.

**Closed by bjorn** 2018-03-27 12:50 UTC
