### ISSUE TITLE
macOS: zoom in/out on tileset windows mistakenly uses top-left anchor point

### ISSUE THREAD

**Issue by Bobjt** [bjorn/tiled#2097] opened 2019-03-31 23:52 UTC
Zooming works correctly however in the map window, by using the mouse pointer as the anchor point around which to zoom. If the tileset windows can't be made to anchor zooming around the mouse, center of the screen would be better than top-left.

**Comment by sano98** [comment] 2019-04-01 07:31
Is this possibly a duplicate of issue #2039?

**Comment by Bobjt** [comment] 2019-04-01 22:21
Yep.

**Comment by bjorn** [comment] 2019-04-02 10:00
Indeed, the zooming implementation based on QTableView is hacky. :-(

Closing this duplicate.

**Closed by bjorn** 2019-04-02 10:00 UTC
