### ISSUE TITLE
Preview image when you have 'insert a tile' tool selected on an object layer

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1498] opened 2017-03-19 00:23 UTC
### Request

I didn't know you would see a preview image when you hold your mouse button down, I was expecting the same UI as the stamp brush. But that feature needs to be on without even having your mouse button down, just when you select the 'insert a tile' tool.

Wouldn't take too much time to dev
### Illustration

https://gyazo.com/ff8927e0cdfe375bef146430846c4e29
(may contain violent mouse movement)

### Reason

Convenience & consistency

**Comment by bjorn** [comment] 2017-03-20 11:14
Duplicate of #537.

> Wouldn't take too much time to dev

While you may be right, please avoid writing things like that. If you think it doesn't take much time, then why don't you just do it?

**Closed by bjorn** 2017-03-20 11:14 UTC
