### ISSUE TITLE
Many problems with v1.3.3 on Mac

### ISSUE THREAD

**Issue by kennycason** [bjorn/tiled#2774] opened 2020-03-20 23:24 UTC
Hi, Thanks for working on Tiled. I've been using it for many years! I believe I have donated before, but will be soon again!

I just wanted to report that there seems to be numerous breaks in the recent 1.3.3 release for Mac.
Honestly, there are so many errors that it would take me a while to isolate exact causes. I'll try and name a few issues and add some screenshots. I'm able to use Tiled but I have to restart every few minutes. I did not have these issues in previous versions (I don't know how previous)

- The icons in the top for selecting erase, brush, random, etc constantly get stuck in strange states. It is not clear if they are clicked or not. The become dark, unselectable, etc. The states seem indeterministic at times.
![image](https://user-images.githubusercontent.com/2858428/77210452-47411700-6abe-11ea-98e4-94320ff188c2.png)
- Often times for no apparent reason brush/erase will just simply have no effect when drawing on a tiled layer. I've verified that i don't have other areas selected and everything else. 
- Sometimes maps have became. I actually had to git revert a map. I was editing it in 1.3.3. and when I saved the file, every subsequent re-opening of the file resulted in me not being able to perform any edit operations. I git reverted the map and it worked fine after that, hence me thinking it was a corrupted file (i also restarted Tiled).
- the file names become scrambled in the top tab when you click on them and after you save.
![image](https://user-images.githubusercontent.com/2858428/77214131-d3593b80-6aca-11ea-9324-ae1662a8d13f.png)

 
I'll try and find more concrete example and add here as they pop up. But in general it seems that there was some major breaking changes on Mac.

Mac Catalina v10.15.2

**Comment by kennycason** [comment] 2020-03-20 23:28
Within a minute of last restart:
![image](https://user-images.githubusercontent.com/2858428/77213348-c1c26480-6ac7-11ea-808f-e37461059879.png)

**Comment by dogwynn** [comment] 2020-03-28 16:01
I'm running into this issue as well. It looks to be a buffer refresh problem. If you were to resize the window, the artifacts disappear. So, something in the rendering callback behavior for clicking on buttons and a number of other events (saving, etc.) is not correctly re-rendering the GUI to reflect the current state.

**Comment by dogwynn** [comment] 2020-03-28 16:08
I believe this might be a duplicate of #2667

**Comment by dogwynn** [comment] 2020-03-28 16:09
![Turn on Hardware accelerated drawing](https://user-images.githubusercontent.com/1621000/77827591-80900d00-70e4-11ea-84b6-06a68140d9f8.png)

If you turn on "Hardware accelerated drawing (OpenGL)", this seems to fix the problem.

**Comment by kennycason** [comment] 2020-03-31 02:26
@dogwynn thanks a lot for the insight and solution. Turning hardware acceleration worked like a charm for me. :)

**Closed** 2020-03-31 20:21 UTC

**Comment by bjorn** [comment] 2020-03-31 20:29
@kennycason Thanks for the report! Even though it's described as many issues, I think they're likely all related to the repainting issues described in #2667, so I've closed this one along with the other one.

The issue where you had to revert a map stands out a bit, but without further information I wouldn't know where to start looking for the problem. If it ever happens again, be sure to backup the broken file somewhere before reverting it. :-)

I was reluctant to make the above fix, because I think it does make Tiled uglier. But obviously the usability issues caused by the broken repainting are worse. Alternatively, you can switch to the "Tiled Fusion" theme instead of "Native" in the Preferences. Then Tiled doesn't look like other macOS apps, but it may look better. :-)

**Comment by kennycason** [comment] 2020-04-01 06:55
@bjorn thanks! I will check out the themes. I actually didn't know that was an option. 

As to the "corrupt file" issue, I could never reproduce the issue. My guess is that in the confusion of issues, the button state wasn't actually in the state I thought it was in. I.e. I thought it was in paint mode but it wasn't, or something like that. I've never had an issue like that before this.

**Comment by kennycason** [comment] 2020-04-01 06:56
@bjorn update, I like the Tiled Fusion theme. :)
