### ISSUE TITLE
Keyboard - Zoom Adjustment

### ISSUE THREAD

**Issue by laetemn** [bjorn/tiled#1120] opened 2015-10-09 14:45 UTC
I realized that one of the zoom adjustment keys not working.
And something minimal and probably should not hinder users Tiled.
![Keyboard Error](https://cloud.githubusercontent.com/assets/273767/10396829/e51a4b6c-6e7a-11e5-9eae-3dd5e634a991.png)
PS: How do I use the labels in this forum to mark a bug, feature, etc?

**Comment by bjorn** [comment] 2015-10-09 19:10
> PS: How do I use the labels in this forum to mark a bug, feature, etc?

Sorry, only I can manage the labels. :-)

I can't reproduce this issue on Linux, so maybe it's Windows-specific.

**Comment by bjorn** [comment] 2015-10-09 20:10
Hmm, I can't reproduce this on OS X or Windows either. Could it be a problem related to your keyboard layout? Though the layout in your image looks like a regular US layout, just like mine...

**Comment by laetemn** [comment] 2015-10-09 22:34
There are two models of keyboard used in Brazil.
Both follow the standard QWERTY and present the "Ç" button.
The only difference between them is that the ABNT2 keyboard has one more key: Alt Gr.

It is right off the space bar and lets you enter additional symbols that appear in the lower right corner of some keys (the symbols ”º” and “ª” are good examples).

To insert these symbols in a text, just press the Atl Gr key along with the key in which the symbol is.

My keyboard is standard ABNT2, as shown in the image below.
![ABNT2 - Brazilian keyboard](https://cloud.githubusercontent.com/assets/273767/10407092/afac0690-6ebc-11e5-9beb-dcb3fbe84eb4.png)

**Comment by Chaoseiro** [comment] 2015-10-09 22:49
I also have the ABNT layout, and, under Ubuntu 15.04, Tiled 2015-10-09 daily build, both shortcuts does not work (neither from the numpad, neither from the numeric keys)

Zooming does work by using the Menu or by using Ctrl + Mouse Wheel.

I'll try to set up a dev environment and test it again.

**Comment by bjorn** [comment] 2015-10-10 11:21
Hmm, Ubuntu 15.04 comes with Qt 5.4.1. Maybe it was broken with this version of Qt. I've so far been using Qt 5.5 on all systems where I tried to reproduce it.

**Comment by bjorn** [comment] 2015-10-10 11:25
Oh wait, I guess on Windows 10 you were also using Qt 5.5. I've also tried it on Windows 10, but it worked for me. :-S

**Comment by laetemn** [comment] 2015-10-10 11:55
I imagined that the error could be something specific to brasileria version of Windows 10, however, the user Chaoseiro said he has even bigger problems when using the Ubuntu.

So, I think that might be something related to the encoding of characters in ASCII / Hex to the standard ABNT.

**Comment by Chaoseiro** [comment] 2015-10-12 18:54
Hey, I've just tested this in Windows 8 (VM) and I got the same behavior described by @laetemn, so I believe it is indeed some Qt issue.

**Comment by SourceR85** [comment] 2015-12-08 23:07
I can reproduce this with my german keyboard.
It's a problem with Qt 5.5.
Building Tiled with Qt 5.4 solves even this problem.

**Comment by bjorn** [comment] 2018-09-05 16:00
Since @SourceR85 and @Chaoseiro suggested this may be an issue in Qt, I'm wondering if anybody is interested in testing whether this still affects the current latest Tiled version (1.1.6) or the latest snapshot (1.2 Beta). They are built against Qt 5.9.5 on Windows and Linux, and Qt 5.6.3 on macOS (though the snap for Linux is built against Qt 5.5 still).

**Comment by bjorn** [comment] 2019-05-15 13:38
Closing this since no further feedback was provided by reporters and this issue hasn't been reported by anyone else either.

**Closed by bjorn** 2019-05-15 13:38 UTC
Labels: bug
