### ISSUE TITLE
Completely empty windows in macOS

### ISSUE THREAD

**Issue by netmute** [bjorn/tiled#2925] opened 2020-10-25 11:15 UTC
macOS 10.15.7
Tiled 1.4.2 from Homebrew

This is what I see:
<img width="1440" alt="screenshot 2020-10-25 at 12 12 39" src="https://user-images.githubusercontent.com/574582/97105523-9cc84c80-16bb-11eb-877d-8d7409dce9c6.png">

**Comment by bjorn** [comment] 2020-10-25 19:48
Duplicate of #2785.

Can you try whether this problem still occurs with the `Tiled.app` available at https://github.com/bjorn/tiled/actions/runs/304632927?

**Closed** 2020-10-25 19:49 UTC
Labels: bug, macos
