### ISSUE TITLE
"undefined" in file names in snapshots-win download directory

### ISSUE THREAD

**Issue by gheja** [bjorn/tiled#1988] opened 2018-08-01 16:25 UTC
Not sure if intentional or not but some files have the `winundefined` suffix (i.e. `Tiled-2018.07.13-winundefined.7z `) on https://update.mapeditor.org/snapshots-win/

**Comment by bjorn** [comment] 2018-08-01 22:05
Yeah, I noticed this as well but I did not find out why yet. Thanks for opening an issue about it, I should definitely look into this again.

**Comment by bjorn** [comment] 2018-08-15 22:43
I'm a little stumped on this, since the code generating those files names is pretty much identical between the archive and the installer, and the "undefined" only shows up on the archive:

https://github.com/bjorn/tiled/blob/e736570e9d5c5cbbc98dfae717b62f637afb85dd/dist/win/installer.qbs#L26-L33

https://github.com/bjorn/tiled/blob/e736570e9d5c5cbbc98dfae717b62f637afb85dd/dist/archive.qbs#L27-L41

Will need to do some testing on Windows...

**Comment by bjorn** [comment] 2018-09-16 21:06
Tried to reproduce it on Windows, but got "32" instead of "undefined". Maybe it's something that was fixed in Qbs 1.12, which I used whereas the builds on AppVeyor are currently done with Qbs 1.11.1.

**Comment by bjorn** [comment] 2018-09-17 20:38
Yup, updating to the latest Qbs version fixed this long standing issue. :-)

**Closed** 2018-09-17 20:38 UTC
