### ISSUE TITLE
Inconsistent coordinates of rectangles

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1697] opened 2017-08-22 18:29 UTC
I thought I have written a bug with rectangles always being off by it's width & height.
But found out that the coordinates are inconsistent.

### How the issue can be reproduced
Here are the map properties

![image](https://user-images.githubusercontent.com/9143253/29580825-a8c3502e-8777-11e7-999f-5bead51cac38.png)

Here is the rectangle cord:
![image](https://user-images.githubusercontent.com/9143253/29580849-b6c6408c-8777-11e7-9b93-6478b7e6a226.png)
Here is the tile cord:
![image](https://user-images.githubusercontent.com/9143253/29580867-c6abf2bc-8777-11e7-89d0-320db26cc23a.png)

### what happens
As you could see both tiles are touching the top of the map, but the rectangle has a cord of y:64, but the tile has a cord of y:0. The rectangle does not respect the tile render order of 'Left, Down'.

### What behavior I expect instead

I expect both the rectangle and tile respect the render order and start at y:0 if the tile is at the top, or x:0 if the tile is at the most left

### details

Ubuntu 64 bit 16.04.2
tiled version 2017.07.12 (ubuntu has an outdated version of 0.14 so i installed tiled-daily)

**Comment by bjorn** [comment] 2017-09-13 20:37
> I expect both the rectangle and tile respect the render order and start at y:0 if the tile is at the top, or x:0 if the tile is at the most left

I'm sorry for the confusion caused! I would expect the same thing, but unfortunately it's not how it works in Tiled. And it will be tricky to change this without breaking backwards compatibility, since this inconsistency has existed ever since tile objects were introduced:

* Rectangle and ellipse objects have top-left origin.
* Tile objects have bottom-left origin (or, on isometric maps, bottom-center origin).

The solution is probably going to involve implementing configurable object anchor points (#560).

Closing this as duplicate of #91.

**Closed by bjorn** 2017-09-13 20:37 UTC
