### ISSUE TITLE
Can't resize tileset/terrain/et-al windows in macOS Mojave beta 

### ISSUE THREAD

**Issue by Bobjt** [bjorn/tiled#1962] opened 2018-06-23 14:40 UTC
There seems to be an issue in macOS Mojave beta where the tileset and other peripheral windows can't be resized. The main app window continues to resize fine, but the peripheral windows lack the "brail" in the bottom right corner; perhaps that relates to the problem? 

It isn't clear if this is a Mojave regression to be fixed in FCS (Sept. timeframe), or, if it's the result of a bug *fix* in Mojave. I haven't experienced any window-resizing issues in other apps in Mojave, so there might be some nonstandard use case that's biting Tiled.

**Comment by bjorn** [comment] 2018-06-23 20:48
Just to be clear, when you're saying "peripheral windows", you're talking about undocked views? They are indeed a little bit special, but the implementation of this is in Qt. Might be worth opening an issue about on the Qt bug tracker.

**Comment by Bobjt** [comment] 2018-06-23 21:29
Sorry - not using Qt lingo because I don't use that framework. "Windows" are inevitably what Qt is using to implement those "undocked views." 

Honestly, you're much more qualified to file this bug than me, but here goes nothing: https://bugreports.qt.io/browse/QTVSADDINBUG-556

I was required to pick a product amongst a list of 10-15 items; short of picking one at random, my hunch told me you're using Visual Studio tools, so that's what I picked. I may be way off base, however.

**Comment by bjorn** [comment] 2018-06-23 21:34
Heh, that Qt issue is going to raise some eyebrows. I'm not using the Visual Studio Add-in, which is a product that is only relevant on Windows when coding in Visual Studio. But I guess they'll move it to the "Qt" product (where it should have been).

In any case, their first question is usually going to be to ask for a small application that demonstrates the problem. On Monday I can try to ship an example so you can tell me if it's also broken there.

Of course, another option is that I install this Mojave beta. Is that available for anybody or does one need to be part of Apple's developer program?

**Comment by bjorn** [comment] 2018-06-23 21:37
Ah, in fact there already is a Qt issue open about this:

https://bugreports.qt.io/browse/QTBUG-68714

Though it does not mention Mojave, it actually says it's also broken on 10.13.5. That means it's likely a regression in Qt 5.11, and you may have started running into it now that macOS releases are built against that release instead of Qt 5.10.

**Comment by Bobjt** [comment] 2018-06-23 21:43
Thanks, Bjorn. I'm leaving the views docked for now, which isn't a big deal. Watching 68714 for updates.

**Comment by bjorn** [comment] 2018-06-23 21:44
> Thanks, Bjorn. I'm leaving the views docked for now, which isn't a big deal. Watching 68714 for updates.

Cool. Don't hesitate to vote for the issue as well, you never know if it may help put it on their radar. :-)

**Comment by bjorn** [comment] 2018-06-25 19:45
Alright, this issue will be fixed again in Qt 5.11.2, which is planned for August/September 2018. In the meantime, it might make sense to look into switching the development snapshots to Qt 5.10 or maybe even Qt 5.9 (which was an LTS release). But they are using Homebrew to install Qt, which seems to offer only the latest or `qt@5.5`.

**Comment by bjorn** [comment] 2018-07-15 21:52
A new snapshot is out with this fix: https://thorbjorn.itch.io/tiled/devlog/40807/object-placement-preview-on-hover

**Comment by Bobjt** [comment] 2018-07-16 15:38
Sorry to say, but it's still broken in the new snapshot (18-07-13). I'm in the latest beta of 10.14, Mojave 18A326h.

**Comment by bjorn** [comment] 2018-07-16 16:09
@Bobjt Arg, I should have paid a bit closer attention! Qt 5.5.1 is affected by the [exact same issue](https://bugreports.qt.io/browse/QTBUG-46882)... this means that both Qt versions available via Homebrew are affected, so I'll reopen this and probably it will have to wait until Qt 5.11.2 is released, unless we extend the build system to compile a custom version of Qt, but that's going to be very time-consuming and would need to use cache to keep build times reasonable.

**Comment by Bobjt** [comment] 2018-07-16 16:20
Cool. Glad the persistent cause isn't a mystery. I wouldn't spend the extra time unless there's a new wave of squeaky macOS users (other than myself).

**Comment by bjorn** [comment] 2018-07-16 16:23
However, I'll keep using the `qt@5.5` version for now until we have found a good reason to use the latest version of Qt. The problem with using the latest version is that it requires at minimum macOS 10.10 (or even 10.11) to run Tiled, while the version built against Qt 5.5.1 says it required only macOS 10.7.

Eventually I think we should use find a way to use Qt 5.6 until macOS 10.7 has become irrelevant and then move to Qt 5.9 (which will require macOS 10.10).

**Comment by bjorn** [comment] 2018-07-16 16:24
> Cool. Glad the persistent cause isn't a mystery. I wouldn't spend the extra time unless there's a new wave of squeaky macOS users (other than myself).

Well, since recently you are unfortunately [not the only one running into this](https://discourse.mapeditor.org/t/cant-resize-minimap-window/3299). :-)

**Comment by bjorn** [comment] 2018-07-19 15:08
At least for manually created builds I could just use Qt 5.6, so the latest Tiled 1.1.6 release is not affected by this issue.

**Comment by Bobjt** [comment] 2018-07-19 16:22
That would be great. As much as I've tried to work around it, was cowering a bit to face maps lately, regardless :)

**Comment by bjorn** [comment] 2018-08-14 15:43
Tiled 1.1.6 was built against Qt 5.6.3 and so will the next snapshot due to change 69056b06664d97b18957650e8dc58acbd9c7170f. So I think we can close this issue. :-)

**Closed by bjorn** 2018-08-14 15:43 UTC
Labels: bug, qt issue
