### ISSUE TITLE
Copy-Paste in collision editor

### ISSUE THREAD

**Issue by X-Ray-Jin** [bjorn/tiled#2075] opened 2019-02-21 11:58 UTC
I recently recognized I cannot copy paste objects in the collision editor anymore. I am not 100% sure but I think this was working some time ago.

**Comment by bjorn** [comment] 2019-02-21 22:07
Hmm, indeed the copy functionality is broken (paste works, since I can still paste objects that I have copied from a map). Thanks for reporting this issue! I'll look into it as soon as possible (hopefully sometime next week).

**Comment by eevee** [comment] 2019-02-23 13:39
Even worse, Cut removes the selection but _doesn't_ put it on the clipboard.

**Comment by bjorn** [comment] 2019-03-06 14:14
This is a regression caused by the behavior change made in 1.2.1, "Changed Cut, Copy and Delete actions to apply based on selected layer types". Because in the Tile Collision Editor, the current layer wasn't actually marked as selected. I'm fixing this up for Tiled 1.2.3.

**Closed** 2019-03-06 16:33 UTC
Labels: bug

**Comment by mengxiaoduan** [comment] 2019-04-03 06:33
This trobule still in tiled

**Comment by mengxiaoduan** [comment] 2019-04-03 06:34
copy still have problem。I can't copy something well

**Comment by bjorn** [comment] 2019-04-03 07:37
@mengxiaoduan Are you using Tiled 1.2.3?
