### ISSUE TITLE
Crash when trying to add the "maps" docker (win10)

### ISSUE THREAD

**Issue by sruloart** [bjorn/tiled#1066] opened 2015-09-02 12:25 UTC
I've noticed this in the last few builds (can't really say from which one). The "maps" docker is correctly added and displayed. 

More info:
Unhandled exception at 0x00F7DEB0 (Qt5Gui.dll) in tiled.exe: 0xC000041D: An unhandled exception was encountered during a user callback.
Unhandled exception at 0x00F7DEB0 (Qt5Gui.dll) in tiled.exe: 0xC0000005: Access violation reading location 0x0000023C.
00F7DEB0  mov         eax,dword ptr ds:[0000023Ch]

**Comment by bjorn** [comment] 2015-09-02 19:28
Hmm, I booted into Windows 10, compiled that latest `master` against Qt 5.5 / MinGW 4.9.2, launched Tiled and went to View -> Maps to show the dock. But it showed up fine and I could use it to open some map.

Is there any way you could try to follow these steps, and if it does crash for you, run Tiled in the debugger to get more information about it?

**Comment by sruloart** [comment] 2015-09-02 22:15
I don't have all of that installed and properly set-up, but there's a way :) 

But before I try that, would it help if I point out the specific builds involved? 

Version v0.12.3-156-ga26fa41 (08/08/2015, 15mb) and prior versions - work fine. The maps docker points out to the `C:/Program Files (x86)/Tiled/util` folder for some reason, but I guess this is the default behavior? but I don't think that the problem lies there.

The problem began with this build: 
Version v0.13.0-9-ga416e59 (10/08/2015, 16mb) and exists on all of the following versions.

**Comment by bjorn** [comment] 2015-09-07 21:17
Thanks for narrowing it down. Unfortunately, a lot happened between these two daily builds (a26fa416075adad635096716e008529bb44835c7...a416e599fc1a18176d5a4440ddbfb5cf31b65316). So far, I'm not able to reproduce it, but I'll have to look at it again before doing the Tiled 0.14 release.



> The maps docker points out to the `C:/Program Files (x86)/Tiled/util` folder for some reason, but I guess this is the default behavior? but I don't think that the problem lies there.

Yeah, that's not the problem, but it's a small issue that I've also noticed. I'll  have to look at why it is starting in `util` since this simply makes no sense.

Just to make sure, can you tell exactly what you do to crash it? Do you just click on _View -> Views and Toolbars -> Maps_ and boom?

**Comment by sruloart** [comment] 2015-09-08 05:52
Yep, even after I canceled all of the other dockers. It's weird that it doesn't happen on all win10 systems (or that it happens only on mine, go figure), maybe you have something installed that I don't have or maybe I have a different version of a .dll somewhere :| 

I'll take a look around, maybe it has something to do with the changes made to `src/tiled/mapsdock.cpp` but I can't really say yet...

**Comment by bjorn** [comment] 2015-09-21 14:45
Could you try whether the installer found over here has the same problem?

https://ci.appveyor.com/project/bjorn/tiled/build/1.0.585/job/sr7rg819u8ue9bii/artifacts

The main difference is that this build does not ship with the Python plugin. I'd just like to know whether this may be related to the problem.

**Comment by sruloart** [comment] 2015-09-21 15:11
Yeah, it crashes still I'm afraid. Where does Tiled store its old preferences btw? does it have any extra reg keys I can delete? it just seems weird it only happens on my machine :|

**Comment by bjorn** [comment] 2015-09-27 12:23
You can find the settings on Windows in the registry at:
```
HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled
```
Please before you delete it, export it to a file. If deleting it resolves your issue, I'd like to know what the settings were.

**Comment by sruloart** [comment] 2015-09-27 12:38
Yep, that solved it :) 

```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled]
"saveBeforeExecute"="true"
"commandList"=hex(7):00,00
"addedDefaultCommands"="true"

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Automapping]
"WhileDrawing"="false"

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\ExportAsImageDialog]
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,02,00,00,00,00,00,00,00,00,00,03,00,0f,00,\
  00,00,00,00,01,00,67,00,00,00,00,00,04,00,71,00,00,00,00,00,02,00,aa,00,00,\
  00,00,00,03,00,18,00,00,00,00,00,01,00,8d,00,00,00,00,00,04,00,68,00,00,00,\
  00,00,02,00,a1,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,07,00,80,\
  00,29,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Install]
"FirstRun"="2015-06-28"
"RunCount"=dword:00000053

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Interface]
"SnapToGrid"="true"
"SnapToFineGrid"="true"
"HighlightCurrentLayer"="true"
"ShowGrid"="true"
"ShowTileObjectOutlines"="true"
"Language"="en"
"OpenGL"="true"
"ShowTileAnimations"="true"
"ObjectLabelVisibility"=dword:00000000

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\LastPaths]
"Images"="C:/Users/cato/Desktop/walk8/tile2.png"

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\mainwindow]
"geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,02,00,00,00,00,00,ff,00,ff,00,ff,00,f8,00,\
  ff,00,ff,00,ff,00,f8,00,00,00,00,00,07,00,87,00,00,00,00,00,04,00,21,00,00,\
  00,00,00,01,00,d5,00,00,00,00,00,00,00,62,00,00,00,00,00,06,00,83,00,00,00,\
  00,00,03,00,1d,00,00,00,00,00,00,00,00,00,02,00,00,00,00,00,00,00,07,00,80,\
  00,29,00
"state"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,00,\
  00,00,00,00,00,00,ff,00,00,00,00,00,00,00,00,00,fd,00,00,00,00,00,00,00,03,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,01,00,3e,00,00,00,00,00,03,00,c7,00,\
  fc,00,02,00,00,00,00,00,00,00,02,00,fb,00,00,00,00,00,00,00,1c,00,00,00,70,\
  00,00,00,72,00,00,00,6f,00,00,00,70,00,00,00,65,00,00,00,72,00,00,00,74,00,\
  00,00,69,00,00,00,65,00,00,00,73,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,\
  00,6b,00,01,00,00,00,00,00,00,00,1b,00,00,00,00,00,03,00,c7,00,00,00,00,00,\
  00,00,81,00,00,00,ff,00,ff,00,ff,00,fc,00,00,00,00,00,00,00,1b,00,00,00,00,\
  00,03,00,c7,00,00,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,fa,00,ff,00,\
  ff,00,ff,00,ff,00,02,00,00,00,00,00,00,00,02,00,fb,00,00,00,00,00,00,00,18,\
  00,00,00,75,00,00,00,6e,00,00,00,64,00,00,00,6f,00,00,00,56,00,00,00,69,00,\
  00,00,65,00,00,00,77,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,00,\
  00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,69,00,\
  00,00,ff,00,ff,00,ff,00,fb,00,00,00,00,00,00,00,10,00,00,00,4d,00,00,00,61,\
  00,00,00,70,00,00,00,73,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,\
  00,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,84,\
  00,00,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,01,00,00,00,00,00,01,00,17,00,\
  00,00,00,00,03,00,c7,00,fc,00,02,00,00,00,00,00,00,00,03,00,fc,00,00,00,00,\
  00,00,00,1b,00,00,00,00,00,00,00,f5,00,00,00,00,00,00,00,b2,00,01,00,00,00,\
  00,00,14,00,fa,00,00,00,00,00,00,00,02,00,02,00,00,00,00,00,00,00,03,00,fb,\
  00,00,00,00,00,00,00,16,00,00,00,6d,00,00,00,69,00,00,00,6e,00,00,00,69,00,\
  00,00,4d,00,00,00,61,00,00,00,70,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,\
  00,6b,00,01,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,\
  00,00,48,00,00,00,ff,00,ff,00,ff,00,fb,00,00,00,00,00,00,00,16,00,00,00,4f,\
  00,00,00,62,00,00,00,6a,00,00,00,65,00,00,00,63,00,00,00,74,00,00,00,73,00,\
  00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,01,00,00,00,00,00,00,00,00,\
  00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,81,00,00,00,ff,00,ff,00,ff,00,\
  fb,00,00,00,00,00,00,00,12,00,00,00,6c,00,00,00,61,00,00,00,79,00,00,00,65,\
  00,00,00,72,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,01,00,00,00,\
  00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,9d,00,00,00,ff,\
  00,ff,00,ff,00,fc,00,00,00,00,00,01,00,14,00,00,00,00,00,01,00,f7,00,00,00,\
  00,00,00,00,ab,00,01,00,00,00,00,00,14,00,fa,00,00,00,00,00,00,00,01,00,02,\
  00,00,00,00,00,00,00,02,00,fb,00,00,00,00,00,00,00,16,00,00,00,54,00,00,00,\
  65,00,00,00,72,00,00,00,72,00,00,00,61,00,00,00,69,00,00,00,6e,00,00,00,44,\
  00,00,00,6f,00,00,00,63,00,00,00,6b,00,01,00,00,00,00,00,00,00,00,00,ff,00,\
  ff,00,ff,00,ff,00,00,00,00,00,00,00,67,00,00,00,ff,00,ff,00,ff,00,fb,00,00,\
  00,00,00,00,00,16,00,00,00,54,00,00,00,69,00,00,00,6c,00,00,00,65,00,00,00,\
  73,00,00,00,65,00,00,00,74,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,\
  00,01,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,\
  96,00,00,00,ff,00,ff,00,ff,00,fb,00,00,00,00,00,00,00,1c,00,00,00,54,00,00,\
  00,69,00,00,00,6c,00,00,00,65,00,00,00,53,00,00,00,74,00,00,00,61,00,00,00,\
  6d,00,00,00,70,00,00,00,73,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,\
  00,01,00,00,00,00,00,03,00,0f,00,00,00,00,00,00,00,d3,00,00,00,00,00,00,00,\
  95,00,00,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,03,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,fc,00,01,00,00,00,00,00,00,00,01,00,fb,00,00,00,\
  00,00,00,00,16,00,00,00,43,00,00,00,6f,00,00,00,6e,00,00,00,73,00,00,00,6f,\
  00,00,00,6c,00,00,00,65,00,00,00,44,00,00,00,6f,00,00,00,63,00,00,00,6b,00,\
  00,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,51,\
  00,00,00,ff,00,ff,00,ff,00,00,00,00,00,05,00,23,00,00,00,00,00,03,00,c7,00,\
  00,00,00,00,00,00,04,00,00,00,00,00,00,00,04,00,00,00,00,00,00,00,08,00,00,\
  00,00,00,00,00,08,00,fc,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,02,00,\
  00,00,00,00,00,00,02,00,00,00,00,00,00,00,16,00,00,00,6d,00,00,00,61,00,00,\
  00,69,00,00,00,6e,00,00,00,54,00,00,00,6f,00,00,00,6f,00,00,00,6c,00,00,00,\
  42,00,00,00,61,00,00,00,72,00,00,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,\
  00,ff,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  18,00,00,00,74,00,00,00,6f,00,00,00,6f,00,00,00,6c,00,00,00,73,00,00,00,54,\
  00,00,00,6f,00,00,00,6f,00,00,00,6c,00,00,00,42,00,00,00,61,00,00,00,72,00,\
  00,00,00,00,00,00,00,00,00,00,ff,00,ff,00,ff,00,ff,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,29,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Map]
"Orientation"=dword:00000000
"Width"=dword:00000014
"Height"=dword:0000000f
"TileWidth"=dword:00000020
"TileHeight"=dword:00000020

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\MapsDirectory]
"Current"="C:/Program Files (x86)/Tiled/util"

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\ObjectsDock]
"FirstSectionSize"=dword:000000c8

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\recentFiles]
"lastOpenFiles"=hex(7):43,00,3a,00,2f,00,55,00,73,00,65,00,72,00,73,00,2f,00,\
  63,00,61,00,74,00,6f,00,2f,00,44,00,65,00,73,00,6b,00,74,00,6f,00,70,00,2f,\
  00,64,00,65,00,73,00,65,00,72,00,74,00,5f,00,31,00,2e,00,74,00,6d,00,78,00,\
  00,00,00,00
"mapScale"=hex(7):32,00,00,00,00,00
"scrollX"=hex(7):30,00,00,00,00,00
"scrollY"=hex(7):30,00,00,00,00,00
"selectedLayer"=hex(7):31,00,00,00,00,00
"lastActive"="C:/Users/cato/Desktop/desert_1.tmx"
"fileNames"=hex(7):43,00,3a,00,2f,00,55,00,73,00,65,00,72,00,73,00,2f,00,63,00,\
  61,00,74,00,6f,00,2f,00,44,00,65,00,73,00,6b,00,74,00,6f,00,70,00,2f,00,64,\
  00,65,00,73,00,65,00,72,00,74,00,5f,00,31,00,2e,00,74,00,6d,00,78,00,00,00,\
  00,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\recentFiles\recentFiles]
"fileNames"=hex(7):43,00,3a,00,2f,00,50,00,72,00,6f,00,6a,00,65,00,63,00,74,00,\
  73,00,2f,00,4c,00,69,00,76,00,65,00,2f,00,61,00,73,00,73,00,65,00,74,00,73,\
  00,2f,00,69,00,6d,00,61,00,67,00,65,00,73,00,2f,00,74,00,72,00,79,00,32,00,\
  2e,00,74,00,6d,00,78,00,00,00,43,00,3a,00,2f,00,55,00,73,00,65,00,72,00,73,\
  00,2f,00,63,00,61,00,74,00,6f,00,2f,00,44,00,65,00,73,00,6b,00,74,00,6f,00,\
  70,00,2f,00,77,00,61,00,6c,00,6b,00,38,00,2f,00,74,00,72,00,79,00,32,00,2e,\
  00,74,00,6d,00,78,00,00,00,43,00,3a,00,2f,00,55,00,73,00,65,00,72,00,73,00,\
  2f,00,63,00,61,00,74,00,6f,00,2f,00,44,00,65,00,73,00,6b,00,74,00,6f,00,70,\
  00,2f,00,77,00,61,00,6c,00,6b,00,38,00,2f,00,74,00,72,00,79,00,2e,00,74,00,\
  6d,00,78,00,00,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Storage]
"DtdEnabled"="false"
"MapRenderOrder"=dword:00000002

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\TileAnimationEditor]
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,02,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,02,00,9c,00,00,00,00,00,01,00,99,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,02,00,9c,00,00,00,\
  00,00,01,00,99,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,07,00,80,\
  00,29,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\TileCollisionEditor]
"Geometry"=hex:40,00,42,00,79,00,74,00,65,00,41,00,72,00,72,00,61,00,79,00,28,\
  00,01,00,d9,00,d0,00,cb,00,00,00,02,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,01,00,3b,00,00,00,00,00,01,00,53,00,00,\
  00,00,00,00,00,08,00,00,00,00,00,00,00,20,00,00,00,00,00,01,00,33,00,00,00,\
  00,00,01,00,4b,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,07,00,80,\
  00,29,00

[HKEY_CURRENT_USER\SOFTWARE\mapeditor.org\Tiled\Tileset]
"UseTransparentColor"="false"
"TransparentColor"="#ff00ff"
"Spacing"=dword:00000000
"Margin"=dword:00000000
"Type"=dword:00000000
```

**Comment by bjorn** [comment] 2015-09-27 12:49
Hmm, I see you have OpenGL turned on in the settings, while by default it is off. Could that have been the reason for the crash, rather than the visibility of the Maps dock?

**Comment by sruloart** [comment] 2015-09-27 13:11
And I see that the program now just quits as I start it :)

**Comment by sruloart** [comment] 2015-09-27 13:18
And you're right, if I set OpenGL to false again in the registry everything works fine...

**Comment by bjorn** [comment] 2015-09-27 13:44
Alright, thanks for testing! Then just leave OpenGL disabled for now (there really isn't any advantage in using it for most use-cases anyway). I'll close this since this means it's probably a duplicate of  #525.

**Closed by bjorn** 2015-09-27 13:44 UTC
Labels: Bug

**Comment by bjorn** [comment] 2015-09-27 14:13
Hmm, in doing some testing, strange enough it does seem to have something to do with the Maps dock widget. It seems like OpenGL mode is more prone to crash when this widget is visible. No idea why though... the backtrace just says something about Qt setting a pen while rendering something.

I'll try switching from QGLWidget to the new QOpenGLWidget to see if that is less prone to crash.

**Comment by bjorn** [comment] 2015-10-09 21:27
I tried replacing QGLWidget with QOpenGLWidget. It seems to make the crash more rare, but it still occurs for me when the Maps dock is open and I maximize the window for example, with the same backtrace.

No Tiled code is involved, but when Qt is busy drawing widgets, it seems suddenly the `state` member of `QPaintEngineEx` is `0x0`, which is bad news for [`QRasterPaintEngine::penChanged`](http://code.woboq.org/qt5/qtbase/src/gui/painting/qpaintengine_raster.cpp.html#_ZN18QRasterPaintEngine10penChangedEv)...

I think this should be reported as a bug against Qt.
