### ISSUE TITLE
Ghost tile selector when using middle-mouse button

### ISSUE THREAD

**Issue by Usiten** [bjorn/tiled#937] opened 2015-05-10 03:12 UTC
A blue ghost tile selector stay on the map when trying to move around with the middle-click grab.
They go away when the cursor goes over them, or when the get out of bounds.
The size of the ghost is almost always the same size as the middle-click displacement size, Vertically and horizontally. 

Using: Tiled Map Editor version 0.11.0
OS: Windows 8.1 64 Bits

![bug](https://cloud.githubusercontent.com/assets/1433628/7552897/a30c3b24-f6d2-11e4-8df5-2c6042851fd9.png)

**Comment by bjorn** [comment] 2015-05-10 08:26
Duplicate of issue #174.

It's an annoying bug, and unfortunately I think it's in the Qt code which makes it a rather daunting thing to look into.

If accelerated rendering (OpenGL) works for you, then you can enable it to get rid of these artifacts. This works because in this mode, the view is always entirely repainted rather than only repainting changing regions.

**Closed by bjorn** 2015-05-10 08:26 UTC
