### ISSUE TITLE
Option to lock objects

### ISSUE THREAD

**Issue by KageJittai** [bjorn/tiled#1063] opened 2015-09-01 15:42 UTC
It would be nice to have the option of locking an object.  Making it uneditable until it is explicitly unlocked.  Some users have complained that moving objects accidentally is too common when modifying an object layer with lots of object.

**Comment by bjorn** [comment] 2015-09-01 16:35
Duplicate of issue #828.

**Closed by bjorn** 2015-09-01 16:35 UTC
