### ISSUE TITLE
Per map object types

### ISSUE THREAD

**Issue by cra0zy** [bjorn/tiled#1263] opened 2016-05-03 19:19 UTC
Just opening this as a separate issue, the idea is to have a per map objecttype.xml, this would allow for:
1) .tmx files would have what custom properties they are using, this would allow parsing of the .tmx file without the need to where objecttype.xml is located in advance
2) different .tmx files would be able to use different default object types without the need to constantly import/export

**Comment by bjorn** [comment] 2016-05-03 19:48
I'm not inclined to implement this because most games will have multiple maps sharing the same set of object types. So, I think this really belongs in a project rather than in each map. Adding support for projects in Tiled is something I plan to get to eventually.

**Comment by bjorn** [comment] 2017-06-05 08:54
I realized this is a duplicate of #228. While that older issue actually predates the `objecttypes.xml` file, it already suggested linking from the map to a file with the types.

**Closed by bjorn** 2017-06-05 08:54 UTC
