### ISSUE TITLE
the Terrain Brush ，Angle problem

### ISSUE THREAD

**Issue by shuketang** [bjorn/tiled#1943] opened 2018-05-08 08:40 UTC
In the example:
![123](https://user-images.githubusercontent.com/39001159/39746702-baae4898-52dd-11e8-866a-14df8d38c0c2.png)

Ours is:
![234](https://user-images.githubusercontent.com/39001159/39746829-22b481b4-52de-11e8-9c8c-5b8ea0854f17.png)

the Terrain Brush，Why is our shape wrong?     So I can't use it correctly the Terrain Brush..........
![333](https://user-images.githubusercontent.com/39001159/39746890-55268fa2-52de-11e8-9744-3cf99ca08d5a.png)

**Comment by bjorn** [comment] 2018-05-08 08:49
You need to set the "Grid Width" and "Grid Height" in the Tileset Properties to match with your tile. In the example, the width is set to 64 and the height to 32. It looks like your tiles should use the same ratio, though possibly higher values.

The reason you need to specify these parameters is because they can't be derived directly from the size of the tile images.

**Comment by shuketang** [comment] 2018-05-08 08:59
set the "Grid Width" and "Grid Height   ：

![123](https://user-images.githubusercontent.com/39001159/39747743-bf678bf8-52e0-11e8-9659-47d013a89e90.png)

The size is also wrong.....

![222](https://user-images.githubusercontent.com/39001159/39747809-e9f3dd7c-52e0-11e8-8bdd-d72d11ddc656.jpg)

How to set the size？

**Comment by bjorn** [comment] 2018-05-08 09:06
Hmm, that looks rather strange actually. To be honest the top and bottom corners should always be exactly aligned regardless of the parameters. Could you share the tileset file that is showing this problem so that I could try to reproduce it?

**Comment by shuketang** [comment] 2018-05-08 09:27
Is it a question of cutting?

**Comment by shuketang** [comment] 2018-05-08 09:29
![222](https://user-images.githubusercontent.com/39001159/39749490-66f27910-52e5-11e8-83a0-89b23fb47b0f.jpg)
![333](https://user-images.githubusercontent.com/39001159/39749492-67139ec4-52e5-11e8-9c49-1aef7522d03a.png)

Feeling different picture size？

**Comment by shuketang** [comment] 2018-05-08 09:37
Do you need a square? image

**Comment by bjorn** [comment] 2018-05-08 09:55
Thanks for providing the example files! Unfortunately due to encoding issues I can only load some of the tiles, but I could reproduce the issue. And wow, that map is HUGE! Did you know that Tiled supports compressing layer data? The map file can be reduced from 45 MB to 6 MB by choosing "Compressed (zlib)" instead of "CSV" in the map properties for "Tile Layer Format".

> Need a square? image

You're right, the overlay currently seems to only render correctly if the tile image is square. That's a bug though, so I will look into fixing that.

**Comment by shuketang** [comment] 2018-05-08 10:01
Yes！We are a huge project.....Can I fix it as soon as possible?We need to re-output the image........

**Comment by bjorn** [comment] 2018-05-08 10:15
> Yes！We are a huge project.....Can I fix it as soon as possible?We need to re-output the image........

Since this is just a visual glitch in the editor that does not affect image output nor the Terrain Tool's functionality, I don't really understand the urgency. Are you supporting Tiled financially /  [as a patron](https://www.patreon.com/bjorn)?

**Comment by shuketang** [comment] 2018-05-08 10:37
of course,How much money is needed to solve this problem~~~^_^

**Comment by shuketang** [comment] 2018-05-08 10:45
wow!!!really!This is a display problem，Does not affect the function, I think it will affect the function.....-_-

**Comment by bjorn** [comment] 2018-05-08 10:45
> of course,How much money is needed to solve this problem~~~^_^

That is hard to say in advance, which is why I am asking for monthly donations to support my continuous work improving and maintaining Tiled, with the hope that I can afford to do this for 2 full days/week.

If you are a large project that depends on Tiled for your workflow, please consider becoming a patron on Patreon (or if you can't, tell me why), at whatever level you are comfortable with financially. It is the best way to ensure this tool will keep improving, and I generally prioritize issues that my patrons are running into.

If you really prefer to do a single donation for putting this bug on my priority list, I'd ask for $100.

**Comment by shuketang** [comment] 2018-05-08 10:58
thinks!Can I privately trust my paypal？I send money.....

**Comment by bjorn** [comment] 2018-05-08 11:04
> thinks!Can I privately trust my paypal？I send money.....

Sure, you can e-mail me at bjorn@mapeditor.org.

**Comment by shuketang** [comment] 2018-05-09 02:41
![123](https://user-images.githubusercontent.com/39001159/39792863-557b115c-5375-11e8-91b8-a26e1d6cc369.jpg)
....Forgive my Chinese English.......-_-

**Comment by bjorn** [comment] 2018-05-09 08:26
> ...Forgive my Chinese English.......-_-

Can you reverse this transaction? Because you've misspelled the e-mail address.

**Comment by bjorn** [comment] 2020-05-13 13:22
@shuketang I've finally looked into this issue and pushed a fix that will be included in the upcoming release and development snapshot.

It would be great if you could still fix the target email address of your donation (not `bjorn@mapedor.org` but `bjorn@mapeditor.org`). The donation is optional but would be really appreciated.

**Closed** 2020-05-13 14:55 UTC
Labels: bug
