### ISSUE TITLE
Ui issues in 1.3.3 (on mac)

### ISSUE THREAD

**Issue by styk-tv** [bjorn/tiled#2778] opened 2020-04-10 12:40 UTC
Hi, I'm having some issues with 1.3.3 on Mac where the buttons pressed do not de-press, each click makes them darker until they go black. As well as some eventually get overlaid. This is not only visual but also affects functionality of Tiled.

Can anyone confirm?

<img width="465" alt="Screenshot 2020-04-09 at 18 16 31" src="https://user-images.githubusercontent.com/838921/78991289-88ae6a80-7b30-11ea-8af2-518c631e6f39.png">

<img width="208" alt="Screenshot 2020-04-09 at 18 09 07" src="https://user-images.githubusercontent.com/838921/78991301-8d731e80-7b30-11ea-8eb7-f1caac9501f9.png">

<img width="1310" alt="Screenshot 2020-04-09 at 18 09 00" src="https://user-images.githubusercontent.com/838921/78991318-9237d280-7b30-11ea-8659-a4ddfda5a4e9.png">

**Comment by bjorn** [comment] 2020-04-12 19:55
Duplicate of #2667. See my last comment there:

> In any case, I've now entirely disabled the unified title bar and tool bar. I think it looks a bit ugly, but that's better than having these painting issues. There's still the alternative to switch the Tiled theme to "Tiled Fusion" in the Preferences, which may look better.

That fix will be out in Tiled 1.3.4, but in the meantime switching to Tiled Fusion also avoids the problem.

**Closed by bjorn** 2020-04-12 19:55 UTC
Labels: bug, macos

**Comment by styk-tv** [comment] 2020-04-15 17:23
@bjorn thanks, i tried to find similar before posting, must have missed it.
