### ISSUE TITLE
64 bit on Windows 10 Crashes a lot

### ISSUE THREAD

**Issue by profK** [bjorn/tiled#1643] opened 2017-07-08 02:40 UTC
That pretty much says it all.
Im on a Surface Book with Windows 10.  64 bit is very unstable. 32 bit seems a lot more stable.

**Comment by bjorn** [comment] 2017-07-08 13:12
You need to be a little more specific if I could have any hope of finding out what could be going wrong. For most people Tiled isn't crashing, even on Windows 10 64-bit, otherwise I'd hear about crashes a lot more often. So we'll need to figure out what it is about your files or what you are doing, that makes Tiled crash.

**Comment by Arcanorum** [comment] 2017-08-06 21:02
Just installed 1.02. Crashes immediately on start.
![image](https://user-images.githubusercontent.com/9785268/29007055-e73e08a8-7af2-11e7-9cdb-a1be05f2d74b.png)

**Comment by Arcanorum** [comment] 2017-08-06 21:11
I already had 0.16.0 installed in the default directory when I installed 1.0.2.
Not sure if the issue is related, but I uninstalled both versions and installed 1.0.2 again, and now it works fine.
Will note any problems that OP might be referring to if I encounter them.

**Comment by Arcanorum** [comment] 2017-08-07 01:16
Can confirm. Has crashed 3 times in the few hours I've been using it now under my normal usage.
I didn't notice anything that causes it.
Memory usage looked stable/no increased usage over time.

Pretty hard to track down given that no error messages are generated...

**Comment by bjorn** [comment] 2018-04-25 21:11
> Not sure if the issue is related, but I uninstalled both versions and installed 1.0.2 again, and now it works fine.

That is exactly the solution in this case, since this crash was caused by incompatible DLLs and EXEs, which came to be due to a change in the installer that unfortunately broke the upgrade process from older versions.

Also, that startup crash is probably not what the original post was about, but unfortunately no further information has been provided by the reporter. Hence closing this issue.

**Closed by bjorn** 2018-04-25 21:11 UTC
Labels: bug, windows
