### ISSUE TITLE
Keyboard shortcuts don't work on Ubuntu

### ISSUE THREAD

**Issue by vadi2** [bjorn/tiled#1497] opened 2017-03-18 03:00 UTC
Me again with more Qt bugs. Keyboard shortcuts don't work on Ubuntu - I'm guessing because Tiled is built with Qt newer than 5.6.2. See corresponding [Qt bugreport](https://bugreports.qt.io/browse/QTBUG-59557).

Also, if you could chip in to http://discourse.appimage.org/t/a-discussion-on-the-chmod-x/162 with your thoughts, that'd be great.

**Comment by ketanhwr** [comment] 2017-03-18 03:34
Hi, this is a duplicate of #1458.

**Comment by bjorn** [comment] 2017-03-18 07:53
Closing cause of duplicate.

@vadi2 Thanks for pointing to the Qt bug report!

> Also, if you could chip in to http://discourse.appimage.org/t/a-discussion-on-the-chmod-x/162 with your thoughts, that'd be great.

I've just liked your post, since I have nothing to add there. The way executable files are handled on Linux is plain ridiculous. If you just want to avoid the `chmod +x` step, you can serve a .zip file with the AppImage. That is how Tiled's AppImages are served through itch.io.

**Closed by bjorn** 2017-03-18 07:53 UTC
