### ISSUE TITLE
Resizing Tileset in image editor does not resize the XML tsx for it

### ISSUE THREAD

**Issue by Tom-III** [bjorn/tiled#1780] opened 2017-10-09 23:17 UTC
```
<?xml version="1.0" encoding="UTF-8"?>
<tileset name="Tileset_Outside" tilewidth="32" tileheight="32" tilecount="512" columns="16">
 <image source="Tileset_Outside.png" width="512" height="1024"/>
</tileset>
```
When previously I went in paint.net and made the image bigger to add more tiles to it.
Latest snapshot, and I opened and closed tiled and it still did not update.
Also the image width and height are not exposed in the tileset properties so the only way to fix this is to manually edit the XML.

**Comment by bjorn** [comment] 2017-10-10 07:23
> Also the image width and height are not exposed in the tileset properties so the only way to fix this is to manually edit the XML.

Actually it should suffice to just re-save the file. Tiled does not currently save maps or tilesets automatically.

What might help in this situation is for Tiled to mark the tileset as changed, so that you will be prompted to save the file on exit. However, currently Tiled can only do this for files that are explicitly opened (whereas tilesets may be loaded in the background only). So in general this might be a complex change.

**Comment by bjorn** [comment] 2017-10-10 07:25
Note however, that there should in general be no need for the `width` and `height` attributes to be updated. At least Tiled does not rely on those values being accurate.

I'll close this issue since it's essentially a duplicate of #1770.

**Closed by bjorn** 2017-10-10 07:25 UTC
