### ISSUE TITLE
Change different properties of flipping = Exception

### ISSUE THREAD

**Issue by Znevs** [bjorn/tiled#975] opened 2015-06-10 21:55 UTC
If select both object and change flipping Horizontal flag, then application is crashed. Sorry for bad English.

![q405dyp](https://cloud.githubusercontent.com/assets/531764/8139501/9082b162-1154-11e5-99a8-d16573d57f22.png)

**Comment by bjorn** [comment] 2015-06-12 20:46
Hmm, strange, I am unable to reproduce this issue. Does it always happen when flipping multiple objects at the same time, or is it maybe a more specific case? Also, did you try older versions of Tiled to see whether this is a new issue?

**Comment by IMMZ** [comment] 2015-06-13 14:47
I'm getting crash too. Steps to reproduce:
1) Create a new map.
2) Put 2 tiled objects on it.
3) Set 'horizontal flipped = true' for one of them (any you want)
4) Select both.
5) Try to change horizontal flipping again
CRASH!
I've made a fix and created a pull request #978 It would be good to see any critique or see it's sucesfully merged.

**Comment by bjorn** [comment] 2015-06-13 18:26
@IMMZ Thanks for finding the extra step needed to reproduce this issue, as well as for the fix!

**Closed** 2015-06-13 19:13 UTC
Labels: Bug
