### ISSUE TITLE
Add support for hexagonal-based terrain transition

### ISSUE THREAD

**Issue by CinchBlue** [bjorn/tiled#2884] opened 2020-08-10 01:51 UTC
As of Version 1.4.2, Tiled does not have support for setting up terrain transitions for hexagonal tiles. I think it would be a nice feature, as it would simply extend what already works to another tile orientation type.

I'm fairly interested in helping out myself. What would this take?

Thanks,
Austin

**Comment by bjorn** [comment] 2020-08-10 06:58
Duplicate of #2824.

**Closed by bjorn** 2020-08-10 06:58 UTC

**Comment by bjorn** [comment] 2020-08-10 07:02
@CinchBlue Thanks for your interest in helping to add this feature! I've tried to describe in https://github.com/bjorn/tiled/issues/2824#issuecomment-643159071 why this will not be trivial, but it's definitely possible and I will try to help you with any questions you may have.
