### ISSUE TITLE
Defining default properties for Object Types

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1030] opened 2015-07-18 14:46 UTC
The Object Types dialog should have a way to add default properties. That way, when you assign an object a predefined Type it should automatically fill in those properties with the default values where they don't exist already.

If a property already exists it should not be changed, or the user could be asked whether he'd like the properties to be reset to the object type's default values.

**Comment by bjorn** [comment] 2015-07-18 18:52
I think this is basically a duplicate of #365 and it is covered by pull request #877

**Closed by bjorn** 2015-07-18 18:52 UTC
