### ISSUE TITLE
error building on osx 10.15

### ISSUE THREAD

**Issue by meniku** [bjorn/tiled#2204] opened 2019-10-16 07:37 UTC
this might be obvious, but I've never worked with qt before.

I followed the build steps from the readme, but that step
```
qbs                               # build Tiled
```

yields the following error in the end of the build process:

```
ERROR: Cannot install files '/Users/wakka/Sync_Nils/Projekte/Contributions/tiled/default/tmxviewer.7fda16ad/$(CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE))/PkgInfo' and '/Users/wakka/Sync_Nils/Projekte/Contributions/tiled/default/tiledquick.183c88d2/$(CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE))/PkgInfo' to the same location '/Users/wakka/Sync_Nils/Projekte/Contributions/tiled/default/install-root/usr/local/$(CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE))/PkgInfo'. If you are attempting to install a directory hierarchy, consider using the qbs.installSourceBase property.
The following products could not be built for configuration default:
csv, defold, defoldcollection, droidcraft, flare, gmx, json, json1, lua, replicaisland, tbin, tengine, test_mapreader, test_staggeredrenderer, tiled, tmxviewer
```

any idea what I may be doing wrong?

**Comment by bjorn** [comment] 2019-10-16 11:08
Hmm, I'll have to try to reproduce this. How did you install Qt and Qbs? If you're following the instructions, probably with `brew install qbs`?

**Comment by meniku** [comment] 2019-10-16 12:15
brew install qbs
and 
brew link qt5 --force

Still have the output open:
```
➜  brew install qbs
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
cayley                  ical-buddy              kpcli                   mame                    mypy

==> Installing dependencies for qbs: qt
==> Installing qbs dependency: qt
==> Downloading https://homebrew.bintray.com/bottles/qt-5.13.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d7/d734eff21324701858605d7896763cbba2440c1350969cd3804d3969b3147d89?__gd
######################################################################## 100.0%
==> Pouring qt-5.13.1.catalina.bottle.tar.gz
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/qt/5.13.1: 9,628 files, 169.2MB
==> Installing qbs
==> Downloading https://homebrew.bintray.com/bottles/qbs-1.14.0.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/87/87e39dfa34e141ddf010dd08236034a35f49f1c449e86ad452523602be226324?__gd
######################################################################## 100.0%
==> Pouring qbs-1.14.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/qbs/1.14.0: 384 files, 6.9MB
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /Users/wakka/Library/Logs/Homebrew/autojump... (64B)
Removing: /Users/wakka/Library/Logs/Homebrew/ncurses... (64B)
Removing: /Users/wakka/Library/Logs/Homebrew/pcre... (64B)
Removing: /Users/wakka/Library/Logs/Homebrew/zsh... (64B)
==> Caveats
==> qt
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

➜  brew link qt5 --force
Linking /usr/local/Cellar/qt/5.13.1... 440 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc
```

I didn't do anything

**Comment by meniku** [comment] 2019-10-16 12:23
I just realized that despite the message, running the command `qbs run -p tiled` actually runs tiled. It looks different than the installed version I have ( darker - maybe due to the osx dark theme I don't know ). 
But anyway seems to work.

I'll close the ticket

**Comment by bjorn** [comment] 2019-10-16 12:35
> just realized that despite the message, running the command `qbs run -p tiled` actually runs tiled.

Right, that's because the problem is due to a conflict in the installation rules for `tmxviewer` and `tiledquick`, neither of which will get built when you just try to run Tiled (then it'll only build Tiled and its dependencies).

Still, running `qbs build` should work as well, so I'm reopening this issue.

**Comment by bjorn** [comment] 2019-10-17 11:59
Hmm, I tried to reproduce this, installing Qbs 1.14.0 and Qt 5.13.1 from Homebrew, setting up with `qbs setup-qt /usr/local/opt/qt/bin/qmake qt-brew`, setting "profiles.qt-brew.baseProfile" to "xcode-maxosx-x86_64" and then compiling using `qbs build profile:qt-brew`, but it built fine.

The commands look a little different than the `README.md` instructions, but that's just because I have other versions of Qt installed as well. Also I can't test on anything newer than macOS 10.13.6 due to my hardware being some years old now. None of this should matter, so not sure what's going wrong here.  :-/

One thing the `README.md` instructions are missing but what I am doing in the `.travis.yml` file, is this command:

    qbs config defaultProfile xcode

Could that be making a difference?

**Comment by meniku** [comment] 2019-10-22 13:47
sorry I have no idea, it's not a problem for me as I can run it and don't really need to have some Mac builds for now. Most likely it's something very specific to my machine so imo you can close the issue

**Comment by bjorn** [comment] 2019-10-22 15:03
I'll include an automated build based on Qbs and Qt from Homebrew in GitHub Actions to check if there are any issues in this regard. An [initial test failed](https://github.com/bjorn/tiled/commit/1daa35e099bd4a7b0a3bc36c6af0284d79c97114/checks?check_suite_id=276061321), probably because of [this issue](https://bugreports.qt.io/browse/QBS-1492) in Qbs. So now I'm wondering how this worked for you at all. :-)

**Comment by HonestQiao** [comment] 2019-10-26 09:53
I can compile it with qt-creator on macos 10.15
ENV:
MacOS: 10.15
QT: 5.13.1
QTCreator: 4.10.1

**Comment by bjorn** [comment] 2019-10-28 09:56
@HonestQiao Didn't you initially run into issues as well? How did you resolve them? By using Qt Creator instead of Qbs from Homebrew?

**Comment by HonestQiao** [comment] 2019-11-01 17:30
> @HonestQiao Didn't you initially run into issues as well? How did you resolve them? By using Qt Creator instead of Qbs from Homebrew?

Yes, I only use Qt Creator to compile Tiled.

**Comment by meniku** [comment] 2020-02-03 18:12
@HonestQiao were you able to build  some kind of release build from QT Creator? I can run/debug from within QT Creator, but I'm struggling a bit with creating a proper bundle from it.

In the meantime I'm trying to make it work via the `qbs build profile:xcode` command, in the hope to somehow get a proper release package. I think the problem comes from these messages spammed at the beginning of the build process:
```
WARNING: undefined variable EXECUTABLE_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE in variable expansion
WARNING: undefined variable UNLOCALIZED_RESOURCES_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE in variable expansion
WARNING: undefined variable CONTENTS_FOLDER_PATH_SHALLOW_BUNDLE_$(SHALLOW_BUNDLE in variable expansion
WARNING: undefined variable SHALLOW_BUNDLE_$(SWIFT_PLATFORM_TARGET_PREFIX in variable expansion
WARNING: undefined variable LD_RUNPATH_SEARCH_PATHS_$(IS_MACCATALYST in variable expansion
```
I tried to google them, but I couldn't find any proper information. @bjorn do those ring a bell? Any Idea where I have to define them?

**Comment by bjorn** [comment] 2020-02-03 21:03
@meniku Sorry I'm stuck on macOS 10.13. I'll see if I can get macOS builds set up on GitHub Actions so we could verify the process. I'm not sure what problem remained last time I tried this, so I've opened #2750 to get some fresh logs.

**Comment by bjorn** [comment] 2020-02-04 16:39
Alright, [this workflow file](https://github.com/bjorn/tiled/blob/master/.github/workflows/macos-latest.yml) now works on 10.15 based on Qt and Qbs available in Homebrew. But it just compiles Tiled, it doesn't build a distributable yet.

**Comment by bjorn** [comment] 2020-02-05 11:06
@meniku So, I don't recognize those errors. I've just made the macOS workflow file upload the `Tiled.app` as artifact (see e867ae5e7a765112cc35204bf3c1f2b388bb4dc6). Maybe see if that version works for you and if so, try to do those steps locally (you can [find the first built artifact here](https://github.com/bjorn/tiled/actions/runs/35005485)).

Closing this issue since I guess the original issue is gone.

**Closed by bjorn** 2020-02-05 11:06 UTC
Labels: macos
