### ISSUE TITLE
Can't resize sizebar in Mac OSX

### ISSUE THREAD

**Issue by bsabiston** [bjorn/tiled#1964] opened 2018-06-23 21:09 UTC
If I try to widen the sidebar with the layers and tilesets, initially it works.  But as soon as I move the mouse it snaps back to its default width.  Any way to get this to stay where I put it?  This is on OSX 10.13.4 and Tiled 1.1.5.

**Comment by bjorn** [comment] 2018-06-23 21:27
I'll have to see if I can reproduce this.

**Comment by bsabiston** [comment] 2018-06-23 21:29
Actually, nevermind,sorry.  I just quit and restarted and the problem went away.

**Comment by bjorn** [comment] 2018-06-23 21:43
Ah, always tricky to dig into issues that are hard to reproduce... be sure to come back to this when you notice it again, and maybe you have an idea of how to trigger it!

**Comment by bjorn** [comment] 2019-05-08 07:45
Closing this since apparently it didn't happen again for almost a year. :-)

**Closed by bjorn** 2019-05-08 07:45 UTC
Labels: bug, macos
