### ISSUE TITLE
Tiled hangs on startup on macOS 11

### ISSUE THREAD

**Issue by dan-hammond** [bjorn/tiled#2937] opened 2020-11-15 16:01 UTC
Hi,

I recently updated my MacBook to the latest OS. Since updating, Tiled immediately becomes unresponsive once opened. I've tried cleaning up any caches or preferences from my library, and tried reinstalling Tiled, to no avail.

I'm sorry I haven't provided any more information -- I can't think of anything else to share that would help diagnose this issue.

Thanks

**Comment by bjorn** [comment] 2020-11-15 19:08
This issue has been fixed in the development snapshots, so please install the latest snapshot instead of Tiled 1.4.2 for now.

Closing as duplicate of #2845.

I'd like to release Tiled 1.5 in a few weeks, but I'll probably have another look at releasing a Tiled 1.4.3 that runs on Big Sur.

**Closed by bjorn** 2020-11-15 19:08 UTC
