### ISSUE TITLE
Copy and pasting objects not working

### ISSUE THREAD

**Issue by jforkan** [bjorn/tiled#886] opened 2015-02-08 17:38 UTC
Recently upgraded to 0.11.0 on OSX 10.10.2. When I click an object in an object layer and try to copy it, cmd+c does not work and Edit > Copy is greyed out. I haven't come across this issue before using older versions of Tiled.

**Comment by jforkan** [comment] 2015-02-08 17:50
This seems to be fixed in the latest build.

**Comment by bjorn** [comment] 2015-02-08 18:50
@jforkan Hmm, no fix related to this was checked in, so I guess I should still check up on this... Please tell me if you hit the issue again.

**Comment by thelucre** [comment] 2015-03-02 01:43
I'm seeing the issue as well in the nightlies, on OSX 10.10.2

**Comment by bjorn** [comment] 2015-03-02 08:53
@thelucre I could not reproduce it when I shortly checked for this issue. Is there maybe any specific context or steps you could mention to help me reproduce this issue?

**Comment by thelucre** [comment] 2015-03-02 16:14
Apologies. It appears to be fixed here. Thanks!

**Comment by bjorn** [comment] 2015-03-02 19:45
Alright, closing again then. :-)

**Closed by bjorn** 2015-03-02 19:45 UTC
