### ISSUE TITLE
Type field input

### ISSUE THREAD

**Issue by todorone** [bjorn/tiled#1244] opened 2016-04-06 07:08 UTC
Hi,
Some strange issues appear when filling "Type" field of object. Sometimes after hitting some letter input field loses focus as if Enter has been pressed and sometimes when you press some letter it doesn't even appear at input field.

Tiled 0.16.0, Windows 7.

**Comment by bjorn** [comment] 2016-04-06 07:12
Since I can't immediately reproduce your problem, could you maybe play around a bit with it to see if you can narrow down this "sometimes"? It could really help to have a better clue about when this actually happens.

**Comment by todorone** [comment] 2016-04-06 07:17
I think i got it.
Try to add type "Door" to Object Types Editor.
Than type "Door" at objects' type field. Than if you press some letter or even Backspace, type field loses focus...

**Comment by bjorn** [comment] 2016-04-06 07:25
Hey, that's very strange, but I see the same thing. I'll look into it soon. Thanks!

**Comment by bjorn** [comment] 2016-05-30 15:00
I can't reproduce it on Linux.

**Comment by aeonofdiscord** [comment] 2016-06-05 16:09
I'm seeing the same behaviour on Linux (with a Cinnamon desktop), but only when I've set a custom property as in #1295.

**Comment by bjorn** [comment] 2016-06-05 21:05
Hmm, I can still not reproduce this on Linux even if the type has a property (tried with a "Fixture" type with a single "foo" property with default value "bar"). In any case, I did see the issue on Windows and will try to look into it soon.

**Comment by bjorn** [comment] 2016-06-12 13:36
It seems this bug was on the Qt side and it appears to have been fixed in Qt 5.6. Hence, I was only seeing it on Windows while @aeonofdiscord was probably testing it with Qt 5.5 on Linux.

So, this bug will be fixed as soon as Tiled is compiled against Qt 5.6. I'd recommend those affected to use a Tiled snapshot build for now (the latest 32-bit snapshot of Tiled is currently still based on Qt 5.5, but the next build will be based on Qt 5.6).

**Closed by bjorn** 2016-06-12 13:36 UTC
Labels: Bug, Urgent, Windows
