### ISSUE TITLE
Tileset properties crash in 0.16.0

### ISSUE THREAD

**Issue by enricllagostera** [bjorn/tiled#1268] opened 2016-05-06 13:26 UTC
Hello everybody,

I just downloaded the 0.16.0 windows 32-bit version, I'm on Windows 10 64-bit. I need to change the tileset image filename, so that was the feature I was most interested in. I tried to open the Tileset Properties and every time it crashes Tiled. I've included a gif of what is going on.

![](http://i.giphy.com/l0K4iskTQRoxn03xC.gif)

I don't have much more new info, but if you instruct me, I can try to get it.

Cheers.

**Comment by bjorn** [comment] 2016-05-06 13:28
Arg, I am just releasing Tiled 0.16.1 and I don't think it fixes anything like this. Will need to see if I can reproduce it.

**Comment by enricllagostera** [comment] 2016-05-06 13:33
Hmm, is there anything I can do to help figuring this bug out? Any relevant specs I can send to you?

**Comment by bjorn** [comment] 2016-05-06 13:43
Unless you are able to narrow down when this is happening, I'm afraid the main thing you could do to help me is quite a bit of work. You'd have to compile Tiled from source and run it in a debugger, to see where it is crashing exactly.

I've tried arranging my dock widgets like you have it and testing with 32-bit Tiled on 64-bit Windows, but I'm unable to reproduce this crash.

I actually wonder if it is a variation on issue #1153, because that one was related to loading of native file icons in Qt, and the "Filename" property does also try to display the native file icon.

**Comment by enricllagostera** [comment] 2016-05-06 13:53
Ok, I'll try to do the compiling and debugging later in the weekend. 
Some other things that might help (?):

- The tmx file was created in another version of Tiled (0.10.2).
- I had moved the tileset file to another location before and then had to copy it again to the original location to be able to re-open this .tmx file.
- I tried with OpenGL both enabled and disabled and behaviour stayed the same.

Is it possible to somehow disable this Filename icon only? I can run it here and test.

**Comment by bjorn** [comment] 2016-05-06 14:10
> Is it possible to somehow disable this Filename icon only? I can run it here and test.

If you compile Tiled yourself, you can disable the file name icon by changing line 167 (`return mIconProvider.icon(QFileInfo(filePath))`) in `variantpropertymanager.cpp` to just `return QIcon()`.

**Comment by enricllagostera** [comment] 2016-05-06 15:32
Ok, I'll try to do it then. I'll let you know the results.

**Comment by bjorn** [comment] 2016-05-06 15:33
Alright. If it's related to the icon, it will get resolved once Qt 5.6.1 is released and I manage to make the releases work against that.

**Comment by bjorn** [comment] 2016-06-13 07:32
This issue is fixed in the current [snapshot builds](https://update.mapeditor.org/snapshots-win/) (starting from tiled-0.16.1006), which are compiled against Qt 5.6.1. I'll probably make a Tiled 0.16.2 release with these fixes sometime soon.

**Closed by bjorn** 2016-06-13 07:32 UTC
Labels: Bug, Windows
