### ISSUE TITLE
The UI is always blank

### ISSUE THREAD

**Issue by damozhang** [bjorn/tiled#2785] opened 2020-04-21 07:36 UTC
I use the app on macOS 10.15.4. The UI is always blank.
I have tried to disable the dark mode but the issue still there.

<img width="1234" alt="Screen Shot 2020-04-21 at 12 31 12 AM" src="https://user-images.githubusercontent.com/244297/79838232-884f7400-8367-11ea-8480-2e07ac4c474f.png">

**Comment by bjorn** [comment] 2020-04-21 07:38
Wow, I've never seen that before. Did you try both the latest release (1.3.4) and the development snapshot?

Did you ever successfully use an older version of Tiled, and if so which version?

**Comment by damozhang** [comment] 2020-04-21 17:45
> Wow, I've never seen that before. Did you try both the latest release (1.3.4) and the development snapshot?
> 
> Did you ever successfully use an older version of Tiled, and if so which version?

I have tried version 1.3.3 and 1.3.4 and it's always been blank.

**Comment by damozhang** [comment] 2020-04-21 17:50
> Did you try both the latest release (1.3.4) and the development snapshot?

I just tried the Tiled for macOS (snapshot). The problem remains.

<img width="1227" alt="Screen Shot 2020-04-21 at 10 47 44 AM" src="https://user-images.githubusercontent.com/244297/79896977-e8710500-83bd-11ea-8aa7-e48deaef12f3.png">

**Comment by bjorn** [comment] 2020-04-21 18:55
Thanks for trying out some different versions! Too bad we didn't find one yet that works.

Could you please also try [Tiled 1.2.5](https://github.com/bjorn/tiled/releases/tag/v1.2.5)? It was built against Qt 5.9 rather than 5.12, just to check if this is potentially some regression there. If that still does not fix the issue, I'll try to make a build with latest Qt available.

Unfortunately I can't test on macOS 10.15 myself since my Mac Mini is too old for this version. Though I think in general Tiled works fine on macOS for most people, so I wonder what's going on here...

**Comment by damozhang** [comment] 2020-04-21 20:03
> Could you please also try [Tiled 1.2.5](https://github.com/bjorn/tiled/releases/tag/v1.2.5)? It was built against Qt 5.9 rather than 5.12, just to check if this is potentially some regression there. If that still does not fix the issue, I'll try to make a build with latest Qt available.

The version 1.2.5 works!

**Comment by bjorn** [comment] 2020-07-12 11:50
According to @astrochili the last version without this issue was Tiled 1.3.1, which was built against Qt 5.12.5. Due to other fixes I don't think reverting to this older Qt version is a good idea, but it's worth trying if that's where the issue is rather than it being due to a change in Tiled.

**Comment by astrochili** [comment] 2020-07-12 12:00
> Would you be able to try this out locally? I can also try making a build of the latest Tiled against Qt 5.12.5 so you can test if the problem is in Qt.

@bjorn I can try the build with the older QT of course, just give me some instructions or links to download.

**Comment by bjorn** [comment] 2020-07-12 12:10
@astrochili That's great! You can download and install Qt 5.12.5 using the [Qt Online Installer](https://www.qt.io/download-qt-installer) (make sure to only install the macOS version of Qt). You may need to set up a Qt account to get it to download. You also need Xcode installed and clone Tiled somewhere of course.

Along with the selected version of Qt, the installer also installs Qt Creator. Open this IDE and then open the top-level `tiled.qbs` file. It should by default offer to configure the project using the installed version of Qt. You can press Run (Command+R) to run Tiled.

**Comment by astrochili** [comment] 2020-07-13 18:52
> @astrochili That's great! You can download and install Qt 5.12.5 using the [Qt Online Installer](https://www.qt.io/download-qt-installer) (make sure to only install the macOS version of Qt). You may need to set up a Qt account to get it to download. You also need Xcode installed and clone Tiled somewhere of course.
> 
> Along with the selected version of Qt, the installer also installs Qt Creator. Open this IDE and then open the top-level `tiled.qbs` file. It should by default offer to configure the project using the installed version of Qt. You can press Run (Command+R) to run Tiled.

I installed Qt 5.12.5 and opened tiled.qbs. When I press Run button I got error "No Executable Specified". Which run configuration I should select?

**Comment by bjorn** [comment] 2020-07-13 19:49
> I installed Qt 5.12.5 and opened tiled.qbs. When I press Run button I got error "No Executable Specified". Which run configuration I should select?

Hmm, normally there should be only one run configuration by default, called "tiled". It's really strange to see essentially all the others except that one. I guess you can try adding one for "tiled" in the Projects view. If the message persists, try to first just press the Build button and press the Run button after the build has finished.

**Comment by astrochili** [comment] 2020-07-14 21:51
> > I installed Qt 5.12.5 and opened tiled.qbs. When I press Run button I got error "No Executable Specified". Which run configuration I should select?
> 
> Hmm, normally there should be only one run configuration by default, called "tiled". It's really strange to see essentially all the others except that one. I guess you can try adding one for "tiled" in the Projects view. If the message persists, try to first just press the Build button and press the Run button after the build has finished.

Wow, that’s not so easy. Following this instruction I received new errors. I'll send you message via Discrod, I think we could connect and I will share the screen.

**Comment by netmute** [comment] 2020-10-26 06:33
@bjorn In reply to your answer to #2925, the version you linked works.

**Comment by bjorn** [comment] 2020-10-27 21:30
@netmute Alright, thanks for testing! Just to make sure, this should mean that the bug is also fixed in the latest development snapshot available [on itch.io](https://thorbjorn.itch.io/tiled) (currently 2020.10.08). If you could verify that I'd say we can close this issue.

**Comment by netmute** [comment] 2020-10-28 19:25
@bjorn 
The latest development snapshot (2020.10.08) is blank again 😢  
The test snapshot (2020.10.28) from itch works fine.

**Comment by bjorn** [comment] 2020-10-28 19:31
@netmute It's sad that the 2020.10.08 snapshot is still broken, given that it's also based on Qt 5.15.1. This means it probably has something to do with another part of the build system... possibly the version of Xcode used.

But the good news is that the new snapshots I've been setting up since yesterday no longer have this problem! These are built on GitHub Actions, which is able to build and upload 4 snapshots in little over 10 minutes. Unfortunately there is still an issue preventing me from replacing the snapshots with the test snapshots, but I hope to have that resolved soon.

**Comment by bjorn** [comment] 2020-10-28 22:01
Should be fixed in latest snapshot!

**Closed by bjorn** 2020-10-28 22:01 UTC
Labels: bug, macos, qt issue
