### ISSUE TITLE
App crash when i changed settings.

### ISSUE THREAD

**Issue by loursbourg** [bjorn/tiled#910] opened 2015-04-02 15:39 UTC
Hello,
I encountered a bug when I was trying to change language into english from the settings tab, I saw some check box where there reads something like OpenGL if i remember, i felt so curious to see what would happen if i check it, i couldn't resist how delicious was that check box.
Yes i did it, I checked, Everything was so cool, I felt relieved because i checked that awesome checkbox,
Then baaaam,
Tiled crashed (see attached screen ) and when ever i try to open it again it freezes for some seconds, then that error comes again, I think the problem is that my laptop doesn't support open gl and it would be better if this option was uncheckable when the PC doesn't support openGL.
hopefully you fix this so soon.
![2015-04-02_16-23-47](https://cloud.githubusercontent.com/assets/11773373/6967372/24104daa-d95f-11e4-8eb4-663cb62d0d81.png)

**Comment by bjorn** [comment] 2015-04-02 18:57
I totally understand your temptation in enabling this fancy option. Unfortunately, this kind of instabilities is the reason I have to leave it off by default. But also, Tiled simply does not benefit a lot from this kind of acceleration anyway.

You can get Tiled to run again by running it from the command line, passing the `--disable-opengl` option, as follows:

```
tiled --disable-opengl
```

Tiled already tries to detect whether OpenGL is available. I could look into doing something like only keeping it enabled when Tiled closes without crashing.

**Comment by loursbourg** [comment] 2015-04-02 19:53
Thank you so much for fast reply.
Am gonna try this when I am home.  And by the way I am an Arabic native
speaker. And I would like to help to improve tiled by translating it to
Arabic. This can populate tiled a little.  Of course this is up to you
whether to accept this tiny effort to help tiled  or refuse it.

**Comment by bjorn** [comment] 2015-04-02 20:03
@loursbourg I would happily accept a translation to Arabic, but please don't underestimate the effort required to translate Tiled entirely! Anyway there is of course no rush so you can take your time and translate a little bit more every day.

Do you know how translating Qt applications work? If you've got Qt installed then you can:

* Open `tiled_en.ts` in Qt Linguist
* Change the Target Language to Arabic in Edit -> Translation File Settings...
* Save the file as `tiled_ar.ts`
* Translate the strings in the file, keeping an eye on the suggestions and consistency checks to speed up the process

Alternatively, the translation can be made on Transifex:

* Go to https://www.transifex.com/projects/p/tiled/
* Add language Arabic / request to Join the translators for this language
* I will approve and then you can proceed to use the online editor for making translations

**Comment by bjorn** [comment] 2015-04-02 20:08
I realized the above instructions would generally be helpful so I now put them on the wiki:

https://github.com/bjorn/tiled/wiki/Translating-Tiled

Then we can also keep it up to date with other notes.

**Comment by loursbourg** [comment] 2015-04-02 20:44
Yeah well. Arabic is right to left language so tiled has to be flipped
horizontally in order to act friendly with Arabic. And talking about
flipping. Some languages starts from different directions than English.
Chinese is top to bottom language. so this might ruin the GUI. ( eg. Text
out of buttons. Left aligned texts act weirdly). So keep that in mind . And
maybe you should refer to this point in the wiki  as a note. And thanks.
On Apr 2, 2015 9:08 PM, "Thorbjørn Lindeijer" <notifications@github.com>
wrote:
>
> I realized the above instructions would generally be helpful so I now put
them on the wiki:

**Comment by bjorn** [comment] 2015-04-02 20:54
Tiled already has a Hebrew translation showing that horizontal flipping is generally handled fine by the Qt framework. Sadly the Hebrew translation is out of date since Tiled 0.9.

Going top to bottom in Chinese is optional. You'll see most Chinese websites simply using left-to-right text, and so does Tiled (a Chinese translation is already available).

**Comment by loursbourg** [comment] 2015-04-02 21:19
Well  good then.

**Comment by loursbourg** [comment] 2015-04-02 21:31
I added a request in transifex. And now am waiting your approval.

**Comment by bjorn** [comment] 2015-04-03 08:05
> I added a request in transifex. And now am waiting your approval.

Approved!

**Comment by loursbourg** [comment] 2015-04-03 14:41
I already started translating using QT linguist. And I am translating.

**Comment by bjorn** [comment] 2015-05-05 13:07
@loursbourg How is it going with the translating? Tiled 0.12 is now in string freeze and if you expect to finish it soon I could still include your translation in the release. It's no problem if you don't have time, just let me know.

**Comment by loursbourg** [comment] 2015-05-05 20:19
i have finished the translation so long ago, and it is ready so here is it
in the attachments.
i added the _DZ suffix to set the country name to Algeria in the language
select drop down menu.

**Comment by bjorn** [comment] 2015-05-05 20:25
@loursbourg Github issues does not support attachments. If you want to send it to me by mail please write to bjorn@lindeijer.nl, thanks!

**Comment by bjorn** [comment] 2015-09-15 14:03
I'll close this issue since it's a duplicate of #525.

@loursbourg Are you interested in updating the translation to include the changed strings in Tiled 0.13 and 0.14, btw?

**Closed by bjorn** 2015-09-15 14:03 UTC
Labels: Bug, Windows
