### ISSUE TITLE
Error when trying to compile on Raspbian

### ISSUE THREAD

**Issue by Kakiking** [bjorn/tiled#2880] opened 2020-08-06 20:28 UTC
I'm using a Raspberry Pi 3B+ with Raspbian Buster.
The snap version of tiled didnt work, so I thought abou compiling it on my own...
`qbs setup-toolchains --detect` worked fine
Traceback:
```
Trying to detect gcc...
Profile 'gcc' created for '/usr/bin/gcc'.
Trying to detect clang...
Profile 'clang' created for '/usr/bin/clang'.
```
But `qbs setup-qt --detect` returned an error:
```
Creating profile 'qt-5-11-3'.
Setting profile 'gcc' as the base profile for this profile.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5VulkanSupport.prl' for module 'QtVulkanSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5FontDatabaseSupport.prl' for module 'QtFontDatabaseSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5KmsSupport.prl' for module 'QtKmsSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5LinuxAccessibilitySupport.prl' for module 'QtLinuxAccessibilitySupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5InputSupport.prl' for module 'QtInputSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5PlatformCompositorSupport.prl' for module 'QtPlatformCompositorSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5Bootstrap.prl' for module 'QtBootstrap' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5ThemeSupport.prl' for module 'QtThemeSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5FbSupport.prl' for module 'QtFbSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5DeviceDiscoverySupport.prl' for module 'QtDeviceDiscoverySupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5EglSupport.prl' for module 'QtEglSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5AccessibilitySupport.prl' for module 'QtAccessibilitySupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5EventDispatcherSupport.prl' for module 'QtEventDispatcherSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5ServiceSupport.prl' for module 'QtServiceSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
Could not open prl file '/usr/lib/arm-linux-gnueabihf/libQt5EdidSupport.prl' for module 'QtEdidSupport' (No such file or directory), and failed to deduce the library file path. This module will likely not be usable by qbs.
```
Hope this will get fixed soon(by the way Official Raspbian support would be really nice)

**Comment by bjorn** [comment] 2020-08-07 07:43
@Kakiking Why did you close the issue?

Regarding the output of `qbs setup-qt --detect`, I don't see any errors there, just messages about missing files that don't appear fatal. Did you try to actually compile Tiled?

**Comment by Kakiking** [comment] 2020-08-07 07:46
```
pi@raspberrypi:~/tiled $ qbs
Build graph does not yet exist for configuration 'default'. Starting from scratch.
Resolving project for configuration default
ERROR: /home/pi/tiled/dist/distribute.qbs:10:1 Error while handling product 'distribute':
/home/pi/tiled/dist/distribute.qbs:16:5 Dependency 'Qt.core' not found for product 'distribute'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiled/libtiled.qbs:3:1 Error while handling product 'libtiled':
/home/pi/tiled/src/libtiled/libtiled.qbs:7:5 Dependency 'Qt.gui' not found for product 'libtiled'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiledquick/libtiledquick.qbs:3:1 Error while handling product 'libtiledquick':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'libtiledquick'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiledquick/libtiledquick.qbs:8:5 Dependency 'Qt.quick' not found for product 'libtiledquick'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/csv/csv.qbs:3:1 Error while handling product 'csv':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'csv'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'csv'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/defold/defold.qbs:3:1 Error while handling product 'defold':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'defold'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'defold'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/defoldcollection/defoldcollection.qbs:3:1 Error while handling product 'defoldcollection':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'defoldcollection'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'defoldcollection'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/droidcraft/droidcraft.qbs:3:1 Error while handling product 'droidcraft':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'droidcraft'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'droidcraft'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/flare/flare.qbs:3:1 Error while handling product 'flare':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'flare'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'flare'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/gmx/gmx.qbs:3:1 Error while handling product 'gmx':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'gmx'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'gmx'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/json/json.qbs:3:1 Error while handling product 'json':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'json'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'json'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/json1/json1.qbs:3:1 Error while handling product 'json1':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'json1'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'json1'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/lua/lua.qbs:3:1 Error while handling product 'lua':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'lua'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'lua'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/replicaisland/replicaisland.qbs:3:1 Error while handling product 'replicaisland':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'replicaisland'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'replicaisland'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/tbin/tbin.qbs:3:1 Error while handling product 'tbin':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tbin'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'tbin'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/plugins/tengine/tengine.qbs:3:1 Error while handling product 'tengine':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tengine'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/qbs/imports/TiledPlugin.qbs:6:5 Dependency 'Qt.gui' not found for product 'tengine'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/qtpropertybrowser/qtpropertybrowser.qbs:3:1 Error while handling product 'qtpropertybrowser':
/home/pi/tiled/src/qtpropertybrowser/qtpropertybrowser.qbs:7:5 Dependency 'Qt.widgets' not found for product 'qtpropertybrowser'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/qtsingleapplication/qtsingleapplication.qbs:3:1 Error while handling product 'qtsingleapplication':
/home/pi/tiled/src/qtsingleapplication/qtsingleapplication.qbs:7:5 Dependency 'Qt.widgets' not found for product 'qtsingleapplication'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/terraingenerator/terraingenerator.qbs:3:1 Error while handling product 'terraingenerator':
/usr/share/qbs/imports/qbs/base/QtGuiApplication.qbs:34:5 Dependency 'Qt.gui' not found for product 'terraingenerator'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'terraingenerator'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tiled/tiled.qbs:6:1 Error while handling product 'tiled':
/usr/share/qbs/imports/qbs/base/QtGuiApplication.qbs:34:5 Dependency 'Qt.gui' not found for product 'tiled'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tiled'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/qtsingleapplication/qtsingleapplication.qbs:21:9 Dependency 'Qt.network' not found for product 'tiled'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tiled/tiled.qbs:16:5 Dependency 'Qt.core' not found for product 'tiled'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tiledquickplugin/tiledquickplugin.qbs:3:1 Error while handling product 'tiledquickplugin':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tiledquickplugin'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiledquick/libtiledquick.qbs:55:9 Dependency 'Qt.quick' not found for product 'tiledquickplugin'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tiledquickplugin/tiledquickplugin.qbs:9:5 Dependency 'Qt.qml' not found for product 'tiledquickplugin'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tmxrasterizer/tmxrasterizer.qbs:3:1 Error while handling product 'tmxrasterizer':
/usr/share/qbs/imports/qbs/base/QtGuiApplication.qbs:34:5 Dependency 'Qt.gui' not found for product 'tmxrasterizer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tmxrasterizer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tmxviewer/tmxviewer.qbs:3:1 Error while handling product 'tmxviewer':
/usr/share/qbs/imports/qbs/base/QtGuiApplication.qbs:34:5 Dependency 'Qt.gui' not found for product 'tmxviewer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'tmxviewer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/src/tmxviewer/tmxviewer.qbs:7:5 Dependency 'Qt.widgets' not found for product 'tmxviewer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/tests/mapreader/mapreader.qbs:3:1 Error while handling product 'test_mapreader':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'test_mapreader'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/tests/mapreader/mapreader.qbs:8:5 Dependency 'Qt.testlib' not found for product 'test_mapreader'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/tests/staggeredrenderer/staggeredrenderer.qbs:3:1 Error while handling product 'test_staggeredrenderer':
/home/pi/tiled/src/libtiled/libtiled.qbs:151:9 Dependency 'Qt.gui' not found for product 'test_staggeredrenderer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/tests/staggeredrenderer/staggeredrenderer.qbs:8:5 Dependency 'Qt.testlib' not found for product 'test_staggeredrenderer'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
/home/pi/tiled/translations/translations.qbs:3:1 Error while handling product 'translations':
/home/pi/tiled/translations/translations.qbs:16:5 Dependency 'Qt.core' not found for product 'translations'.
Please create a Qt profile using the qbs-setup-qt tool if you haven't already done so.
pi@raspberrypi:~/tiled $ 
```
Error when trying to compile :(

**Comment by bjorn** [comment] 2020-08-07 08:10
@Kakiking Hmm, not sure what could cause it. Which version of `qbs` are you using?

Also, you can try whether `qmake` works instead, just run:
```
qmake
make
```

**Comment by Kakiking** [comment] 2020-08-07 08:12
Version of qbs: `Version: 1.12.2+dfsg-2+rpi1`

**Comment by bjorn** [comment] 2020-08-07 08:33
@Kakiking That is quite old. You could try with a newer version of qbs if you compile that from source as well, but it will be easier to try compiling Tiled with qmake instead.

**Comment by Kakiking** [comment] 2020-08-07 08:41
I'm compiling tiled with qmake right now :)
It will take some time.....

**Comment by Kakiking** [comment] 2020-08-07 09:35
```
.o moc_tilesetterrainmodel.o moc_tilesetwangsetmodel.o moc_tilesetview.o moc_tilestampmanager.o moc_tilestampmodel.o moc_tilestampsdock.o moc_tmxmapformat.o moc_toolmanager.o moc_treeviewcombobox.o moc_undodock.o moc_varianteditorfactory.o moc_variantpropertymanager.o moc_wangbrush.o moc_wangcolormodel.o moc_wangcolorview.o moc_wangsetview.o moc_wangsetmodel.o moc_wangdock.o moc_wangtemplatemodel.o moc_wangtemplateview.o moc_worlddocument.o moc_worldmovemaptool.o moc_zoomable.o   -L/home/pi/tiled/src/tiled/../../lib -ltiled -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread -latomic 
/usr/bin/ld: actionmanager.o: file not recognized: file truncated
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1487: ../../bin/tiled] Fehler 1
make[2]: Verzeichnis „/home/pi/tiled/src/tiled“ wird verlassen
make[1]: *** [Makefile:93: sub-tiled-make_first-ordered] Fehler 2
make[1]: Verzeichnis „/home/pi/tiled/src“ wird verlassen
make: *** [Makefile:46: sub-src-make_first-ordered] Fehler 2
pi@raspberrypi:~/tiled $ 
```Didnt work @bjorn

**Comment by bjorn** [comment] 2020-08-07 09:43
```
> /usr/bin/ld: actionmanager.o: file not recognized: file truncated
```

That's a strange error. Did you run out of disk space?

**Comment by Kakiking** [comment] 2020-08-07 09:43
I dont think so, I should have 32GB in total

**Comment by Kakiking** [comment] 2020-08-07 09:45
I have 15GB free in /home/pi folder, so that cant be the problem...

**Comment by bjorn** [comment] 2020-08-07 09:55
Can you try to remove this file and running `make` again? It seems weird that this would affect only that object file.

**Comment by Kakiking** [comment] 2020-08-07 09:58
I couldn't delete it :thinking: 
This file seems to be broken, it has 0 bytes...

**Comment by bjorn** [comment] 2020-08-07 10:00
Hmm, what error does it give when you try to delete it? It could be a permissions problem, a hardware issue or software issue.

**Comment by Kakiking** [comment] 2020-08-07 10:02
`actionmanager.o: Error getting information for file »/home/pi/tiled/src/tiled/actionmanager.o«: file or directory not found`

**Comment by bjorn** [comment] 2020-08-07 10:03
I guess just clone Tiled to a different directory and try again... if this keeps happening maybe try a different SD card. :-/

**Comment by Kakiking** [comment] 2020-08-07 10:04
ok, I'll try

**Comment by Kakiking** [comment] 2020-08-07 11:58
@bjorn I think it's compiled now :)
YaY!

**Comment by Kakiking** [comment] 2020-08-07 11:59
Now I still have a question...
How to install it?

**Comment by bjorn** [comment] 2020-08-07 12:13
> How to install it?

Hmm, well you could run `make install` as root or with `sudo`, but you don't need to and I would advise against it because the files would enter your system unmanaged. By default it would install in `/usr/local` prefix.

I'd suggest just running the binary directly from where the compiler put it.

Since it did eventually compile and the other issue is likely caused by too old Qbs version, I'll close this issue now.

**Closed by bjorn** 2020-08-07 12:13 UTC
