### ISSUE TITLE
json map files immediately fail to load (corrupt)

### ISSUE THREAD

**Issue by johnfn** [bjorn/tiled#1858] opened 2018-01-17 06:01 UTC
Tiled version 1.1.1

### How to reproduce:

1. Add a single tile to your map
2. Save as json
3. Open json file

### Error:

"Corrupt layer data for layer 'Tile Layer 1'"

**Comment by saeedakhter** [comment] 2018-01-30 06:06
@johnfn can you attach or upload your .json somewhere?  I was unable to reproduce, but there are lots of combinations for settings while creating a new map.

**Comment by bjorn** [comment] 2018-01-30 09:24
This must be about an infinite map. It appears I have forgotten to adjust the JSON reader in change fca34d6ad4d1216a31bdbf757749aa3505bca9e8... For me it wasn't even giving an error, but got stuck in an infinite loop trying to decompress "nothing". I just fixed that in change 27f7eca9e182281326f037d7361ffa678c67c493. Now I'll adjust the JSON reader to handle infinite maps.

**Comment by bjorn** [comment] 2018-01-30 10:26
Fix will be released with Tiled 1.1.2 (and in the next development snapshot of course).

**Closed** 2018-01-30 13:29 UTC
Labels: bug
