### ISSUE TITLE
Blank windows on macOS Mojave

### ISSUE THREAD

**Issue by astrochili** [bjorn/tiled#2857] opened 2020-07-12 07:51 UTC
Hello guys,
I installed Tiled on macOS 10.14.6 and got the blank windows.

![Screenshot 2020-07-12 at 10 44 42](https://user-images.githubusercontent.com/4752473/87241594-71cc2c80-c42d-11ea-999e-b414447ac39f.png)

Does anyone have this trouble before?
I tried all the versions of Tiled and confirm that this problem starts from 1.3.2. Version 1.3.1 works perfect.

**Comment by bjorn** [comment] 2020-07-12 11:48
Hmm, thanks for digging into the old versions to find out when this broke! Looking at the changelog for 1.3.2, this item stands out as something that might be related to this:

> Updated Qt from 5.12.5 to 5.12.6

Maybe there was some kind of regression. Since Tiled 1.3.5 the releases are done based on Qt 5.12.8, but it could be that this regression remains. Would you be able to try this out locally? I can also try making a build of the latest Tiled against Qt 5.12.5 so you can test if the problem is in Qt.

In any case, please make further comments regarding this issue at #2785. I'll close this issue now since it's a duplicate.

**Closed by bjorn** 2020-07-12 11:48 UTC
Labels: bug, macos
