### ISSUE TITLE
Menubar missing in the editor when building on Ubuntu 14.04

### ISSUE THREAD

**Issue by Madsy** [bjorn/tiled#1157] opened 2015-12-19 06:20 UTC
The menubar (file, edit, view, map, layer, help) does not display here. I tried to build both fc2373f (master) and 851edff (0.14 branch/tag). No luck with either. The toolbars show up, though.

I'm on Ubuntu 14.04 and my Qt version is 5.2

The way I built tiled was:

git clone https://github.com/bjorn/tiled && cd tiled
mkdir BUILD && cd BUILD
qmake -makefile -Wall -unix ../tiled.pro
make
./bin/tiled

Is this a bug or has the menubar been replaced by the toolbar?

For good measure, here's a screenshot. https://i.imgur.com/tHW7zkA.png

**Comment by bjorn** [comment] 2015-12-19 14:13
This is a duplicate of issue #1132, see comments there for possible workarounds. If you never use Unity, the best solution is probably to deinstall `appmenu-qt5`.

**Closed by bjorn** 2015-12-19 14:13 UTC

**Comment by Madsy** [comment] 2015-12-20 05:13
Ah, silly me I searched everywhere except for on the issue tracker. Sorry for wasting your time, bjorn.  Removing appmenu-qt5 did wonders, thank you.

**Comment by bjorn** [comment] 2015-12-20 10:36
No problem, @Madsy. I hope Ubuntu will find a way to avoid it somehow, since there seem to be quite a few people getting bitten by this...
