### ISSUE TITLE
Occasional pauses when dragging the stamp brush tool

### ISSUE THREAD

**Issue by tcoxon** [bjorn/tiled#918] opened 2015-04-16 10:57 UTC
This is on an 800x800 map with Tiled v0.11.0-64-g0ae2b91 on Windows 64-bit.

Periodically, while dragging the stamp brush over a large map, the brush will pause, lagging behind the mouse cursor. After half a second, it catches up with the mouse cursor. The pauses seem to coincide with Tiled suddenly surging up from 0% to 20% CPU usage in taskmgr.

**Comment by bjorn** [comment] 2015-04-16 12:21
Hmm, this is likely caused by having tile animations turned on. Can you try turning this off to see if it gets rid of the pauses?

**Comment by ArmagonNo1** [comment] 2015-04-16 12:39
I still encounter pausing with the animations turned off (though our tiles don't have animations to speak of). The spikes happen almost every time I let go of the mouse button when placing tiles, even if it's just one or two tiles, the pause is consistently about half a second.

**Comment by bjorn** [comment] 2015-04-16 14:50
Ah, on such a huge map I guess the repainting of the minimap is getting noticable, which I have not been able to move to a thread yet nor is it smart about which area to redraw. In this case, closing the minimap should get rid of the pauses. If you depend on the minimap then either of the before mentioned mechanisms would have to be implemented.

**Comment by ArmagonNo1** [comment] 2015-04-16 14:53
I'll give that a try! I'm not really using the minimap anyway as I typically just zoom in and out of the areas I'm working on.

**Comment by bjorn** [comment] 2015-04-16 20:47
Alright, I've opened #920 about this problem.

**Closed by bjorn** 2015-04-16 20:47 UTC
